/* 
 Copyright (C) 2005-2015 Intalio inc.

 The program(s) herein may be used and/or copied only with
 the written permission of Intalio Inc. or in accordance with
 the terms and conditions stipulated in the agreement/contract
 under which the program(s) have been supplied. 
*/
 var times = {
     'Atlantic/Canary': 'UTC+01:00 Western European Time (Atlantic/Canary)',
     'Australia/Melbourne': 'UTC+10:00 Eastern Standard Time (Victoria) (Australia/Melbourne)',
     'Etc/GMT+9': 'UTC-09:00 GMT-09:00 (Etc/GMT+9)',
     'Etc/GMT+8': 'UTC-08:00 GMT-08:00 (Etc/GMT+8)',
     'Europe/Lisbon': 'UTC+01:00 Western European Time (Europe/Lisbon)',
     'Etc/GMT+3': 'UTC-03:00 GMT-03:00 (Etc/GMT+3)',
     'Etc/GMT+2': 'UTC-02:00 GMT-02:00 (Etc/GMT+2)',
     'Etc/GMT+1': 'UTC-01:00 GMT-01:00 (Etc/GMT+1)',
     'Etc/GMT+0': 'UTC-00:00 GMT+00:00 (Etc/GMT+0)',
     'America/Nipigon': 'UTC-04:00 Eastern Standard Time (America/Nipigon)',
     'Etc/GMT+6': 'UTC-06:00 GMT-06:00 (Etc/GMT+6)',
     'Etc/GMT+5': 'UTC-05:00 GMT-05:00 (Etc/GMT+5)',
     'America/Miquelon': 'UTC-02:00 Pierre & Miquelon Standard Time (America/Miquelon)',
     'Pacific/Wallis': 'UTC+12:00 Wallis & Futuna Time (Pacific/Wallis)',
     'Antarctica/Davis': 'UTC+07:00 Davis Time (Antarctica/Davis)',
     'AGT': 'UTC-03:00 Argentine Time (AGT)',
     'Asia/Dhaka': 'UTC+06:00 Bangladesh Time (Asia/Dhaka)',
     'America/St_Lucia': 'UTC-04:00 Atlantic Standard Time (America/St_Lucia)',
     'Canada/Newfoundland': 'UTC-02:30 Newfoundland Standard Time (Canada/Newfoundland)',
     'SystemV/YST9YDT': 'UTC-08:00 Alaska Standard Time (SystemV/YST9YDT)',
     'Pacific/Rarotonga': 'UTC-10:00 Cook Is. Time (Pacific/Rarotonga)',
     'Asia/Kashgar': 'UTC+08:00 China Standard Time (Asia/Kashgar)',
     'Asia/Kuching': 'UTC+08:00 Malaysia Time (Asia/Kuching)',
     'America/Phoenix': 'UTC-07:00 Mountain Standard Time (America/Phoenix)',
     'Europe/Kaliningrad': 'UTC+03:00 Further-eastern European Time (Europe/Kaliningrad)',
     'Etc/GMT+7': 'UTC-07:00 GMT-07:00 (Etc/GMT+7)',
     'America/Mazatlan': 'UTC-06:00 Mountain Standard Time (America/Mazatlan)',
     'Arctic/Longyearbyen': 'UTC+02:00 Central European Time (Arctic/Longyearbyen)',
     'Europe/Guernsey': 'UTC+01:00 Greenwich Mean Time (Europe/Guernsey)',
     'GB': 'UTC+01:00 Greenwich Mean Time (GB)',
     'Antarctica/Rothera': 'UTC-03:00 Rothera Time (Antarctica/Rothera)',
     'Europe/Stockholm': 'UTC+02:00 Central European Time (Europe/Stockholm)',
     'Pacific/Fiji': 'UTC+12:00 Fiji Time (Pacific/Fiji)',
     'Pacific/Apia': 'UTC+13:00 West Samoa Time (Pacific/Apia)',
     'Etc/GMT+4': 'UTC-04:00 GMT-04:00 (Etc/GMT+4)',
     'Pacific/Pago_Pago': 'UTC-11:00 Samoa Standard Time (Pacific/Pago_Pago)',
     'Asia/Rangoon': 'UTC+06:30 Myanmar Time (Asia/Rangoon)',
     'America/Mexico_City': 'UTC-05:00 Central Standard Time (America/Mexico_City)',
     'America/Ensenada': 'UTC-07:00 Pacific Standard Time (America/Ensenada)',
     'America/Puerto_Rico': 'UTC-04:00 Atlantic Standard Time (America/Puerto_Rico)',
     'Indian/Mauritius': 'UTC+04:00 Mauritius Time (Indian/Mauritius)',
     'Europe/Berlin': 'UTC+02:00 Central European Time (Europe/Berlin)',
     'Europe/Zurich': 'UTC+02:00 Central European Time (Europe/Zurich)',
     'Africa/Casablanca': 'UTC+01:00 Western European Time (Africa/Casablanca)',
     'Antarctica/Macquarie': 'UTC+11:00 Macquarie Island Time (Antarctica/Macquarie)',
     'Europe/Warsaw': 'UTC+02:00 Central European Time (Europe/Warsaw)',
     'Asia/Krasnoyarsk': 'UTC+08:00 Krasnoyarsk Time (Asia/Krasnoyarsk)',
     'BET': 'UTC-03:00 Brasilia Time (BET)',
     'Australia/Canberra': 'UTC+10:00 Eastern Standard Time (New South Wales) (Australia/Canberra)',
     'America/Coral_Harbour': 'UTC-05:00 Eastern Standard Time (America/Coral_Harbour)',
     'Atlantic/Bermuda': 'UTC-03:00 Atlantic Standard Time (Atlantic/Bermuda)',
     'Asia/Ujung_Pandang': 'UTC+08:00 Central Indonesia Time (Asia/Ujung_Pandang)',
     'America/Araguaina': 'UTC-03:00 Brasilia Time (America/Araguaina)',
     'Asia/Tehran': 'UTC+04:30 Iran Standard Time (Asia/Tehran)',
     'Asia/Saigon': 'UTC+07:00 Indochina Time (Asia/Saigon)',
     'Asia/Baku': 'UTC+05:00 Azerbaijan Time (Asia/Baku)',
     'America/St_Barthelemy': 'UTC-04:00 Atlantic Standard Time (America/St_Barthelemy)',
     'America/Porto_Acre': 'UTC-05:00 Acre Time (America/Porto_Acre)',
     'America/Santarem': 'UTC-03:00 Brasilia Time (America/Santarem)',
     'Australia/NSW': 'UTC+10:00 Eastern Standard Time (New South Wales) (Australia/NSW)',
     'Libya': 'UTC+02:00 Eastern European Time (Libya)',
     'America/Danmarkshavn': 'UTC-00:00 Greenwich Mean Time (America/Danmarkshavn)',
     'America/Scoresbysund': 'UTC-00:00 Eastern Greenland Time (America/Scoresbysund)',
     'America/Eirunepe': 'UTC-05:00 Acre Time (America/Eirunepe)',
     'America/Caracas': 'UTC-04:30 Venezuela Time (America/Caracas)',
     'Asia/Baghdad': 'UTC+03:00 Arabia Standard Time (Asia/Baghdad)',
     'Africa/Monrovia': 'UTC-00:00 Greenwich Mean Time (Africa/Monrovia)',
     'America/St_Vincent': 'UTC-04:00 Atlantic Standard Time (America/St_Vincent)',
     'Portugal': 'UTC+01:00 Western European Time (Portugal)',
     'Europe/Tiraspol': 'UTC+03:00 Eastern European Time (Europe/Tiraspol)',
     'America/Vancouver': 'UTC-07:00 Pacific Standard Time (America/Vancouver)',
     'Asia/Ho_Chi_Minh': 'UTC+07:00 Indochina Time (Asia/Ho_Chi_Minh)',
     'Europe/Busingen': 'UTC+02:00 Central European Time (Europe/Busingen)',
     'SystemV/CST6CDT': 'UTC-05:00 Central Standard Time (SystemV/CST6CDT)',
     'Etc/GMT0': 'UTC-00:00 GMT+00:00 (Etc/GMT0)',
     'SystemV/AST4ADT': 'UTC-03:00 Atlantic Standard Time (SystemV/AST4ADT)',
     'Asia/Thimphu': 'UTC+06:00 Bhutan Time (Asia/Thimphu)',
     'Africa/Ouagadougou': 'UTC-00:00 Greenwich Mean Time (Africa/Ouagadougou)',
     'America/Belize': 'UTC-06:00 Central Standard Time (America/Belize)',
     'America/Port_of_Spain': 'UTC-04:00 Atlantic Standard Time (America/Port_of_Spain)',
     'Greenwich': 'UTC-00:00 Greenwich Mean Time (Greenwich)',
     'America/Mendoza': 'UTC-03:00 Argentine Time (America/Mendoza)',
     'Asia/Tokyo': 'UTC+09:00 Japan Standard Time (Asia/Tokyo)',
     'Pacific/Kiritimati': 'UTC+14:00 Line Is. Time (Pacific/Kiritimati)',
     'Australia/Sydney': 'UTC+10:00 Eastern Standard Time (New South Wales) (Australia/Sydney)',
     'SystemV/EST5': 'UTC-05:00 Eastern Standard Time (SystemV/EST5)',
     'Europe/Riga': 'UTC+03:00 Eastern European Time (Europe/Riga)',
     'CST': 'UTC-05:00 Central Standard Time (CST)',
     'Asia/Dili': 'UTC+09:00 Timor-Leste Time (Asia/Dili)',
     'Africa/Mbabane': 'UTC+02:00 South Africa Standard Time (Africa/Mbabane)',
     'Asia/Oral': 'UTC+05:00 Oral Time (Asia/Oral)',
     'Asia/Aden': 'UTC+03:00 Arabia Standard Time (Asia/Aden)',
     'Europe/Isle_of_Man': 'UTC+01:00 Greenwich Mean Time (Europe/Isle_of_Man)',
     'Europe/Istanbul': 'UTC+03:00 Eastern European Time (Europe/Istanbul)',
     'Asia/Magadan': 'UTC+12:00 Magadan Time (Asia/Magadan)',
     'BST': 'UTC+06:00 Bangladesh Time (BST)',
     'Australia/Lindeman': 'UTC+10:00 Eastern Standard Time (Queensland) (Australia/Lindeman)',
     'US/Michigan': 'UTC-04:00 Eastern Standard Time (US/Michigan)',
     'JST': 'UTC+09:00 Japan Standard Time (JST)',
     'America/Bogota': 'UTC-05:00 Colombia Time (America/Bogota)',
     'Africa/Asmara': 'UTC+03:00 Eastern African Time (Africa/Asmara)',
     'America/Chicago': 'UTC-05:00 Central Standard Time (America/Chicago)',
     'Pacific/Kwajalein': 'UTC+12:00 Marshall Islands Time (Pacific/Kwajalein)',
     'Australia/Broken_Hill': 'UTC+09:30 Central Standard Time (South Australia/New South Wales) (Australia/Broken_Hill)',
     'America/Cuiaba': 'UTC-04:00 Amazon Time (America/Cuiaba)',
     'Indian/Christmas': 'UTC+07:00 Christmas Island Time (Indian/Christmas)',
     'Asia/Jayapura': 'UTC+09:00 East Indonesia Time (Asia/Jayapura)',
     'Europe/Brussels': 'UTC+02:00 Central European Time (Europe/Brussels)',
     'Iceland': 'UTC-00:00 Greenwich Mean Time (Iceland)',
     'Asia/Chongqing': 'UTC+08:00 China Standard Time (Asia/Chongqing)',
     'America/Argentina/Cordoba': 'UTC-03:00 Argentine Time (America/Argentina/Cordoba)',
     'Canada/Pacific': 'UTC-07:00 Pacific Standard Time (Canada/Pacific)',
     'America/Noronha': 'UTC-02:00 Fernando de Noronha Time (America/Noronha)',
     'Europe/Podgorica': 'UTC+02:00 Central European Time (Europe/Podgorica)',
     'Africa/Algiers': 'UTC+01:00 Central European Time (Africa/Algiers)',
     'Africa/Harare': 'UTC+02:00 Central African Time (Africa/Harare)',
     'Africa/Ndjamena': 'UTC+01:00 Western African Time (Africa/Ndjamena)',
     'America/Costa_Rica': 'UTC-06:00 Central Standard Time (America/Costa_Rica)',
     'Europe/Ljubljana': 'UTC+02:00 Central European Time (Europe/Ljubljana)',
     'CAT': 'UTC+02:00 Central African Time (CAT)',
     'Indian/Mayotte': 'UTC+03:00 Eastern African Time (Indian/Mayotte)',
     'Asia/Phnom_Penh': 'UTC+07:00 Indochina Time (Asia/Phnom_Penh)',
     'America/Managua': 'UTC-06:00 Central Standard Time (America/Managua)',
     'America/Pangnirtung': 'UTC-04:00 Eastern Standard Time (America/Pangnirtung)',
     'Etc/GMT+12': 'UTC-12:00 GMT-12:00 (Etc/GMT+12)',
     'America/Tijuana': 'UTC-07:00 Pacific Standard Time (America/Tijuana)',
     'Pacific/Fakaofo': 'UTC+13:00 Tokelau Time (Pacific/Fakaofo)',
     'America/Martinique': 'UTC-04:00 Atlantic Standard Time (America/Martinique)',
     'America/Antigua': 'UTC-04:00 Atlantic Standard Time (America/Antigua)',
     'America/Indiana/Indianapolis': 'UTC-04:00 Eastern Standard Time (America/Indiana/Indianapolis)',
     'America/Argentina/La_Rioja': 'UTC-03:00 Argentine Time (America/Argentina/La_Rioja)',
     'Pacific/Tahiti': 'UTC-10:00 Tahiti Time (Pacific/Tahiti)',
     'Asia/Brunei': 'UTC+08:00 Brunei Time (Asia/Brunei)',
     'Europe/Zagreb': 'UTC+02:00 Central European Time (Europe/Zagreb)',
     'America/Asuncion': 'UTC-04:00 Paraguay Time (America/Asuncion)',
     'Europe/Vienna': 'UTC+02:00 Central European Time (Europe/Vienna)',
     'Mexico/General': 'UTC-05:00 Central Standard Time (Mexico/General)',
     'Australia/Hobart': 'UTC+10:00 Eastern Standard Time (Tasmania) (Australia/Hobart)',
     'Europe/Belfast': 'UTC+01:00 Greenwich Mean Time (Europe/Belfast)',
     'America/Juneau': 'UTC-08:00 Alaska Standard Time (America/Juneau)',
     'America/Inuvik': 'UTC-06:00 Mountain Standard Time (America/Inuvik)',
     'America/Ojinaga': 'UTC-06:00 Mountain Standard Time (America/Ojinaga)',
     'America/Montreal': 'UTC-04:00 Eastern Standard Time (America/Montreal)',
     'Asia/Seoul': 'UTC+09:00 Korea Standard Time (Asia/Seoul)',
     'Brazil/Acre': 'UTC-05:00 Acre Time (Brazil/Acre)',
     'Indian/Comoro': 'UTC+03:00 Eastern African Time (Indian/Comoro)',
     'Europe/Paris': 'UTC+02:00 Central European Time (Europe/Paris)',
     'Hongkong': 'UTC+08:00 Hong Kong Time (Hongkong)',
     'SystemV/AST4': 'UTC-04:00 Atlantic Standard Time (SystemV/AST4)',
     'Europe/Tallinn': 'UTC+03:00 Eastern European Time (Europe/Tallinn)',
     'Indian/Mahe': 'UTC+04:00 Seychelles Time (Indian/Mahe)',
     'Asia/Calcutta': 'UTC+05:30 India Standard Time (Asia/Calcutta)',
     'Australia/South': 'UTC+09:30 Central Standard Time (South Australia) (Australia/South)',
     'America/Argentina/Jujuy': 'UTC-03:00 Argentine Time (America/Argentina/Jujuy)',
     'MIT': 'UTC+13:00 West Samoa Time (MIT)',
     'America/Creston': 'UTC-07:00 Mountain Standard Time (America/Creston)',
     'America/Adak': 'UTC-09:00 Hawaii-Aleutian Standard Time (America/Adak)',
     'Asia/Singapore': 'UTC+08:00 Singapore Time (Asia/Singapore)',
     'PRC': 'UTC+08:00 China Standard Time (PRC)',
     'Africa/Nairobi': 'UTC+03:00 Eastern African Time (Africa/Nairobi)',
     'Asia/Thimbu': 'UTC+06:00 Bhutan Time (Asia/Thimbu)',
     'America/Maceio': 'UTC-03:00 Brasilia Time (America/Maceio)',
     'PRT': 'UTC-04:00 Atlantic Standard Time (PRT)',
     'Africa/Cairo': 'UTC+03:00 Eastern European Time (Africa/Cairo)',
     'Europe/Moscow': 'UTC+04:00 Moscow Standard Time (Europe/Moscow)',
     'Antarctica/Palmer': 'UTC-04:00 Chile Time (Antarctica/Palmer)',
     'Asia/Ulaanbaatar': 'UTC+08:00 Ulaanbaatar Time (Asia/Ulaanbaatar)',
     'America/Rainy_River': 'UTC-05:00 Central Standard Time (America/Rainy_River)',
     'Africa/Kampala': 'UTC+03:00 Eastern African Time (Africa/Kampala)',
     'Asia/Colombo': 'UTC+05:30 India Standard Time (Asia/Colombo)',
     'Canada/Mountain': 'UTC-06:00 Mountain Standard Time (Canada/Mountain)',
     'Australia/Adelaide': 'UTC+09:30 Central Standard Time (South Australia) (Australia/Adelaide)',
     'America/Cambridge_Bay': 'UTC-06:00 Mountain Standard Time (America/Cambridge_Bay)',
     'Africa/Luanda': 'UTC+01:00 Western African Time (Africa/Luanda)',
     'US/Pacific-New': 'UTC-07:00 Pacific Standard Time (US/Pacific-New)',
     'Pacific/Chatham': 'UTC+12:45 Chatham Standard Time (Pacific/Chatham)',
     'America/Indiana/Winamac': 'UTC-04:00 Eastern Standard Time (America/Indiana/Winamac)',
     'Asia/Dacca': 'UTC+06:00 Bangladesh Time (Asia/Dacca)',
     'America/Cordoba': 'UTC-03:00 Argentine Time (America/Cordoba)',
     'Asia/Tbilisi': 'UTC+04:00 Georgia Time (Asia/Tbilisi)',
     'Europe/Gibraltar': 'UTC+02:00 Central European Time (Europe/Gibraltar)',
     'Asia/Karachi': 'UTC+05:00 Pakistan Time (Asia/Karachi)',
     'Asia/Harbin': 'UTC+08:00 China Standard Time (Asia/Harbin)',
     'Australia/Lord_Howe': 'UTC+10:30 Lord Howe Standard Time (Australia/Lord_Howe)',
     'Etc/GMT-9': 'UTC+09:00 GMT+09:00 (Etc/GMT-9)',
     'Etc/GMT-8': 'UTC+08:00 GMT+08:00 (Etc/GMT-8)',
     'America/Bahia_Banderas': 'UTC-05:00 Central Standard Time (America/Bahia_Banderas)',
     'Etc/GMT-1': 'UTC+01:00 GMT+01:00 (Etc/GMT-1)',
     'Australia/Tasmania': 'UTC+10:00 Eastern Standard Time (Tasmania) (Australia/Tasmania)',
     'Etc/GMT-3': 'UTC+03:00 GMT+03:00 (Etc/GMT-3)',
     'Etc/GMT-2': 'UTC+02:00 GMT+02:00 (Etc/GMT-2)',
     'Etc/GMT-5': 'UTC+05:00 GMT+05:00 (Etc/GMT-5)',
     'Etc/GMT-4': 'UTC+04:00 GMT+04:00 (Etc/GMT-4)',
     'Etc/GMT-7': 'UTC+07:00 GMT+07:00 (Etc/GMT-7)',
     'Etc/GMT-6': 'UTC+06:00 GMT+06:00 (Etc/GMT-6)',
     'America/Boa_Vista': 'UTC-04:00 Amazon Time (America/Boa_Vista)',
     'Eire': 'UTC+01:00 Greenwich Mean Time (Eire)',
     'America/Lima': 'UTC-05:00 Peru Time (America/Lima)',
     'Indian/Reunion': 'UTC+04:00 Reunion Time (Indian/Reunion)',
     'Atlantic/Stanley': 'UTC-03:00 Falkland Is. Time (Atlantic/Stanley)',
     'CET': 'UTC+02:00 Central European Time (CET)',
     'Etc/GMT-13': 'UTC+13:00 GMT+13:00 (Etc/GMT-13)',
     'America/Blanc-Sablon': 'UTC-04:00 Atlantic Standard Time (America/Blanc-Sablon)',
     'Australia/West': 'UTC+08:00 Western Standard Time (Australia) (Australia/West)',
     'Antarctica/Syowa': 'UTC+03:00 Syowa Time (Antarctica/Syowa)',
     'America/Jamaica': 'UTC-05:00 Eastern Standard Time (America/Jamaica)',
     'Europe/Kiev': 'UTC+03:00 Eastern European Time (Europe/Kiev)',
     'Europe/Budapest': 'UTC+02:00 Central European Time (Europe/Budapest)',
     'Canada/Eastern': 'UTC-04:00 Eastern Standard Time (Canada/Eastern)',
     'Pacific/Midway': 'UTC-11:00 Samoa Standard Time (Pacific/Midway)',
     'America/Goose_Bay': 'UTC-03:00 Atlantic Standard Time (America/Goose_Bay)',
     'Australia/Victoria': 'UTC+10:00 Eastern Standard Time (Victoria) (Australia/Victoria)',
     'Asia/Amman': 'UTC+03:00 Arabia Standard Time (Asia/Amman)',
     'Asia/Sakhalin': 'UTC+11:00 Sakhalin Time (Asia/Sakhalin)',
     'Africa/Windhoek': 'UTC+01:00 Western African Time (Africa/Windhoek)',
     'US/Pacific': 'UTC-07:00 Pacific Standard Time (US/Pacific)',
     'SST': 'UTC+11:00 Solomon Is. Time (SST)',
     'AST': 'UTC-08:00 Alaska Standard Time (AST)',
     'America/Sitka': 'UTC-08:00 Alaska Standard Time (America/Sitka)',
     'Asia/Katmandu': 'UTC+05:45 Nepal Time (Asia/Katmandu)',
     'America/Guyana': 'UTC-04:00 Guyana Time (America/Guyana)',
     'Pacific/Pohnpei': 'UTC+11:00 Pohnpei Time (Pacific/Pohnpei)',
     'America/Sao_Paulo': 'UTC-03:00 Brasilia Time (America/Sao_Paulo)',
     'Turkey': 'UTC+03:00 Eastern European Time (Turkey)',
     'Australia/Yancowinna': 'UTC+09:30 Central Standard Time (South Australia/New South Wales) (Australia/Yancowinna)',
     'America/Lower_Princes': 'UTC-04:00 Atlantic Standard Time (America/Lower_Princes)',
     'Australia/Perth': 'UTC+08:00 Western Standard Time (Australia) (Australia/Perth)',
     'Africa/Djibouti': 'UTC+03:00 Eastern African Time (Africa/Djibouti)',
     'Asia/Jakarta': 'UTC+07:00 West Indonesia Time (Asia/Jakarta)',
     'Asia/Pyongyang': 'UTC+09:00 Korea Standard Time (Asia/Pyongyang)',
     'EST5EDT': 'UTC-04:00 Eastern Standard Time (EST5EDT)',
     'CTT': 'UTC+08:00 China Standard Time (CTT)',
     'IST': 'UTC+05:30 India Standard Time (IST)',
     'Africa/Johannesburg': 'UTC+02:00 South Africa Standard Time (Africa/Johannesburg)',
     'Canada/East-Saskatchewan': 'UTC-06:00 Central Standard Time (Canada/East-Saskatchewan)',
     'Asia/Tel_Aviv': 'UTC+03:00 Israel Standard Time (Asia/Tel_Aviv)',
     'Antarctica/Troll': 'UTC+02:00 GMT+00:00 (Antarctica/Troll)',
     'Asia/Istanbul': 'UTC+03:00 Eastern European Time (Asia/Istanbul)',
     'Asia/Irkutsk': 'UTC+09:00 Irkutsk Time (Asia/Irkutsk)',
     'Iran': 'UTC+04:30 Iran Standard Time (Iran)',
     'Australia/ACT': 'UTC+10:00 Eastern Standard Time (New South Wales) (Australia/ACT)',
     'Africa/Niamey': 'UTC+01:00 Western African Time (Africa/Niamey)',
     'Australia/North': 'UTC+09:30 Central Standard Time (Northern Territory) (Australia/North)',
     'America/Belem': 'UTC-03:00 Brasilia Time (America/Belem)',
     'Asia/Bishkek': 'UTC+06:00 Kirgizstan Time (Asia/Bishkek)',
     'Africa/Nouakchott': 'UTC-00:00 Greenwich Mean Time (Africa/Nouakchott)',
     'ECT': 'UTC+02:00 Central European Time (ECT)',
     'Asia/Ashkhabad': 'UTC+05:00 Turkmenistan Time (Asia/Ashkhabad)',
     'Europe/Vilnius': 'UTC+03:00 Eastern European Time (Europe/Vilnius)',
     'America/Cayenne': 'UTC-03:00 French Guiana Time (America/Cayenne)',
     'Africa/Mogadishu': 'UTC+03:00 Eastern African Time (Africa/Mogadishu)',
     'NZ': 'UTC+12:00 New Zealand Standard Time (NZ)',
     'America/Kentucky/Monticello': 'UTC-04:00 Eastern Standard Time (America/Kentucky/Monticello)',
     'America/Rio_Branco': 'UTC-05:00 Acre Time (America/Rio_Branco)',
     'America/Cancun': 'UTC-05:00 Central Standard Time (America/Cancun)',
     'America/Havana': 'UTC-04:00 Cuba Standard Time (America/Havana)',
     'Chile/EasterIsland': 'UTC-06:00 Easter Is. Time (Chile/EasterIsland)',
     'Pacific/Guam': 'UTC+10:00 Chamorro Standard Time (Pacific/Guam)',
     'Pacific/Kosrae': 'UTC+11:00 Kosrae Time (Pacific/Kosrae)',
     'Canada/Atlantic': 'UTC-03:00 Atlantic Standard Time (Canada/Atlantic)',
     'US/Arizona': 'UTC-07:00 Mountain Standard Time (US/Arizona)',
     'Atlantic/Azores': 'UTC-00:00 Azores Time (Atlantic/Azores)',
     'Australia/Eucla': 'UTC+08:45 Central Western Standard Time (Australia) (Australia/Eucla)',
     'Asia/Shanghai': 'UTC+08:00 China Standard Time (Asia/Shanghai)',
     'US/Alaska': 'UTC-08:00 Alaska Standard Time (US/Alaska)',
     'America/Godthab': 'UTC-02:00 Western Greenland Time (America/Godthab)',
     'Asia/Beirut': 'UTC+03:00 Eastern European Time (Asia/Beirut)',
     'Africa/Maputo': 'UTC+02:00 Central African Time (Africa/Maputo)',
     'Asia/Bahrain': 'UTC+03:00 Arabia Standard Time (Asia/Bahrain)',
     'Asia/Ashgabat': 'UTC+05:00 Turkmenistan Time (Asia/Ashgabat)',
     'Asia/Riyadh': 'UTC+03:00 Arabia Standard Time (Asia/Riyadh)',
     'Atlantic/Jan_Mayen': 'UTC+02:00 Central European Time (Atlantic/Jan_Mayen)',
     'PNT': 'UTC-07:00 Mountain Standard Time (PNT)',
     'Atlantic/Faeroe': 'UTC+01:00 Western European Time (Atlantic/Faeroe)',
     'America/Montevideo': 'UTC-03:00 Uruguay Time (America/Montevideo)',
     'America/Anguilla': 'UTC-04:00 Atlantic Standard Time (America/Anguilla)',
     'Asia/Damascus': 'UTC+03:00 Eastern European Time (Asia/Damascus)',
     'America/North_Dakota/Center': 'UTC-05:00 Central Standard Time (America/North_Dakota/Center)',
     'UCT': 'UTC-00:00 Coordinated Universal Time (UCT)',
     'America/Indiana/Vevay': 'UTC-04:00 Eastern Standard Time (America/Indiana/Vevay)',
     'Atlantic/St_Helena': 'UTC-00:00 Greenwich Mean Time (Atlantic/St_Helena)',
     'America/Barbados': 'UTC-04:00 Atlantic Standard Time (America/Barbados)',
     'Europe/Vatican': 'UTC+02:00 Central European Time (Europe/Vatican)',
     'America/Indiana/Vincennes': 'UTC-04:00 Eastern Standard Time (America/Indiana/Vincennes)',
     'Asia/Almaty': 'UTC+06:00 Alma-Ata Time (Asia/Almaty)',
     'Australia/Queensland': 'UTC+10:00 Eastern Standard Time (Queensland) (Australia/Queensland)',
     'America/Santo_Domingo': 'UTC-04:00 Atlantic Standard Time (America/Santo_Domingo)',
     'Africa/Brazzaville': 'UTC+01:00 Western African Time (Africa/Brazzaville)',
     'America/Fort_Wayne': 'UTC-04:00 Eastern Standard Time (America/Fort_Wayne)',
     'America/Nome': 'UTC-08:00 Alaska Standard Time (America/Nome)',
     'Asia/Taipei': 'UTC+08:00 China Standard Time (Asia/Taipei)',
     'America/Yakutat': 'UTC-08:00 Alaska Standard Time (America/Yakutat)',
     'W-SU': 'UTC+04:00 Moscow Standard Time (W-SU)',
     'America/Argentina/Mendoza': 'UTC-03:00 Argentine Time (America/Argentina/Mendoza)',
     'Zulu': 'UTC-00:00 Coordinated Universal Time (Zulu)',
     'Egypt': 'UTC+03:00 Eastern European Time (Egypt)',
     'America/Tortola': 'UTC-04:00 Atlantic Standard Time (America/Tortola)',
     'Etc/UTC': 'UTC-00:00 Coordinated Universal Time (Etc/UTC)',
     'Brazil/East': 'UTC-03:00 Brasilia Time (Brazil/East)',
     'Africa/Asmera': 'UTC+03:00 Eastern African Time (Africa/Asmera)',
     'Antarctica/Mawson': 'UTC+05:00 Mawson Time (Antarctica/Mawson)',
     'America/Buenos_Aires': 'UTC-03:00 Argentine Time (America/Buenos_Aires)',
     'Asia/Kolkata': 'UTC+05:30 India Standard Time (Asia/Kolkata)',
     'Africa/Maseru': 'UTC+02:00 South Africa Standard Time (Africa/Maseru)',
     'America/Atikokan': 'UTC-05:00 Eastern Standard Time (America/Atikokan)',
     'America/St_Johns': 'UTC-02:30 Newfoundland Standard Time (America/St_Johns)',
     'Pacific/Yap': 'UTC+10:00 Chuuk Time (Pacific/Yap)',
     'America/Santa_Isabel': 'UTC-07:00 Pacific Standard Time (America/Santa_Isabel)',
     'America/Atka': 'UTC-09:00 Hawaii-Aleutian Standard Time (America/Atka)',
     'Africa/Libreville': 'UTC+01:00 Western African Time (Africa/Libreville)',
     'Africa/Freetown': 'UTC-00:00 Greenwich Mean Time (Africa/Freetown)',
     'Africa/Bissau': 'UTC-00:00 Greenwich Mean Time (Africa/Bissau)',
     'Europe/Samara': 'UTC+04:00 Samara Time (Europe/Samara)',
     'Europe/Amsterdam': 'UTC+02:00 Central European Time (Europe/Amsterdam)',
     'Europe/Tirane': 'UTC+02:00 Central European Time (Europe/Tirane)',
     'Pacific/Saipan': 'UTC+10:00 Chamorro Standard Time (Pacific/Saipan)',
     'Africa/Abidjan': 'UTC-00:00 Greenwich Mean Time (Africa/Abidjan)',
     'Europe/Zaporozhye': 'UTC+03:00 Eastern European Time (Europe/Zaporozhye)',
     'HST': 'UTC-10:00 Hawaii Standard Time (HST)',
     'America/El_Salvador': 'UTC-06:00 Central Standard Time (America/El_Salvador)',
     'Europe/Madrid': 'UTC+02:00 Central European Time (Europe/Madrid)',
     'Africa/Juba': 'UTC+03:00 Eastern African Time (Africa/Juba)',
     'America/Santiago': 'UTC-04:00 Chile Time (America/Santiago)',
     'America/Argentina/Buenos_Aires': 'UTC-03:00 Argentine Time (America/Argentina/Buenos_Aires)',
     'America/Argentina/San_Luis': 'UTC-03:00 Argentine Time (America/Argentina/San_Luis)',
     'Europe/Skopje': 'UTC+02:00 Central European Time (Europe/Skopje)',
     'WET': 'UTC+01:00 Western European Time (WET)',
     'America/Aruba': 'UTC-04:00 Atlantic Standard Time (America/Aruba)',
     'SystemV/PST8PDT': 'UTC-07:00 Pacific Standard Time (SystemV/PST8PDT)',
     'Navajo': 'UTC-06:00 Mountain Standard Time (Navajo)',
     'America/Indianapolis': 'UTC-04:00 Eastern Standard Time (America/Indianapolis)',
     'America/Regina': 'UTC-06:00 Central Standard Time (America/Regina)',
     'Pacific/Truk': 'UTC+10:00 Chuuk Time (Pacific/Truk)',
     'Pacific/Chuuk': 'UTC+10:00 Chuuk Time (Pacific/Chuuk)',
     'Asia/Khandyga': 'UTC+10:00 Khandyga Time (Asia/Khandyga)',
     'Pacific/Funafuti': 'UTC+12:00 Tuvalu Time (Pacific/Funafuti)',
     'Universal': 'UTC-00:00 Coordinated Universal Time (Universal)',
     'America/Merida': 'UTC-05:00 Central Standard Time (America/Merida)',
     'America/Guatemala': 'UTC-06:00 Central Standard Time (America/Guatemala)',
     'AET': 'UTC+10:00 Eastern Standard Time (New South Wales) (AET)',
     'Africa/Sao_Tome': 'UTC-00:00 Greenwich Mean Time (Africa/Sao_Tome)',
     'Asia/Makassar': 'UTC+08:00 Central Indonesia Time (Asia/Makassar)',
     'Africa/Bujumbura': 'UTC+02:00 Central African Time (Africa/Bujumbura)',
     'Europe/Chisinau': 'UTC+03:00 Eastern European Time (Europe/Chisinau)',
     'America/Monterrey': 'UTC-05:00 Central Standard Time (America/Monterrey)',
     'Asia/Yekaterinburg': 'UTC+06:00 Yekaterinburg Time (Asia/Yekaterinburg)',
     'US/Hawaii': 'UTC-10:00 Hawaii Standard Time (US/Hawaii)',
     'Antarctica/Casey': 'UTC+08:00 Western Standard Time (Australia) (Antarctica/Casey)',
     'Pacific/Enderbury': 'UTC+13:00 Phoenix Is. Time (Pacific/Enderbury)',
     'America/Thule': 'UTC-03:00 Atlantic Standard Time (America/Thule)',
     'America/Louisville': 'UTC-04:00 Eastern Standard Time (America/Louisville)',
     'America/Moncton': 'UTC-03:00 Atlantic Standard Time (America/Moncton)',
     'Europe/Helsinki': 'UTC+03:00 Eastern European Time (Europe/Helsinki)',
     'Atlantic/Cape_Verde': 'UTC-01:00 Cape Verde Time (Atlantic/Cape_Verde)',
     'America/Tegucigalpa': 'UTC-06:00 Central Standard Time (America/Tegucigalpa)',
     'Indian/Cocos': 'UTC+06:30 Cocos Islands Time (Indian/Cocos)',
     'America/Boise': 'UTC-06:00 Mountain Standard Time (America/Boise)',
     'America/Guadeloupe': 'UTC-04:00 Atlantic Standard Time (America/Guadeloupe)',
     'America/Nassau': 'UTC-04:00 Eastern Standard Time (America/Nassau)',
     'Europe/Prague': 'UTC+02:00 Central European Time (Europe/Prague)',
     'America/Halifax': 'UTC-03:00 Atlantic Standard Time (America/Halifax)',
     'Asia/Hovd': 'UTC+07:00 Hovd Time (Asia/Hovd)',
     'Canada/Saskatchewan': 'UTC-06:00 Central Standard Time (Canada/Saskatchewan)',
     'America/Manaus': 'UTC-04:00 Amazon Time (America/Manaus)',
     'America/Rankin_Inlet': 'UTC-05:00 Central Standard Time (America/Rankin_Inlet)',
     'Etc/UCT': 'UTC-00:00 Coordinated Universal Time (Etc/UCT)',
     'GB-Eire': 'UTC+01:00 Greenwich Mean Time (GB-Eire)',
     'Etc/Greenwich': 'UTC-00:00 Greenwich Mean Time (Etc/Greenwich)',
     'America/Catamarca': 'UTC-03:00 Argentine Time (America/Catamarca)',
     'America/North_Dakota/Beulah': 'UTC-05:00 Central Standard Time (America/North_Dakota/Beulah)',
     'America/Chihuahua': 'UTC-06:00 Mountain Standard Time (America/Chihuahua)',
     'America/Iqaluit': 'UTC-04:00 Eastern Standard Time (America/Iqaluit)',
     'America/Argentina/Rio_Gallegos': 'UTC-03:00 Argentine Time (America/Argentina/Rio_Gallegos)',
     'Pacific/Gambier': 'UTC-09:00 Gambier Time (Pacific/Gambier)',
     'Europe/Volgograd': 'UTC+04:00 Volgograd Time (Europe/Volgograd)',
     'Africa/Bamako': 'UTC-00:00 Greenwich Mean Time (Africa/Bamako)',
     'Asia/Novokuznetsk': 'UTC+07:00 Novosibirsk Time (Asia/Novokuznetsk)',
     'Europe/Uzhgorod': 'UTC+03:00 Eastern European Time (Europe/Uzhgorod)',
     'Africa/Banjul': 'UTC-00:00 Greenwich Mean Time (Africa/Banjul)',
     'Asia/Aqtau': 'UTC+05:00 Aqtau Time (Asia/Aqtau)',
     'Pacific/Palau': 'UTC+09:00 Palau Time (Pacific/Palau)',
     'PST': 'UTC-07:00 Pacific Standard Time (PST)',
     'Africa/Malabo': 'UTC+01:00 Western African Time (Africa/Malabo)',
     'Europe/Minsk': 'UTC+03:00 Further-eastern European Time (Europe/Minsk)',
     'PST8PDT': 'UTC-07:00 Pacific Standard Time (PST8PDT)',
     'America/Argentina/ComodRivadavia': 'UTC-03:00 Argentine Time (America/Argentina/ComodRivadavia)',
     'Atlantic/Madeira': 'UTC+01:00 Western European Time (Atlantic/Madeira)',
     'Pacific/Noumea': 'UTC+11:00 New Caledonia Time (Pacific/Noumea)',
     'GMT0': 'UTC-00:00 GMT+00:00 (GMT0)',
     'Africa/Kinshasa': 'UTC+01:00 Western African Time (Africa/Kinshasa)',
     'Europe/Malta': 'UTC+02:00 Central European Time (Europe/Malta)',
     'US/Samoa': 'UTC-11:00 Samoa Standard Time (US/Samoa)',
     'America/Argentina/Ushuaia': 'UTC-03:00 Argentine Time (America/Argentina/Ushuaia)',
     'Asia/Chungking': 'UTC+08:00 China Standard Time (Asia/Chungking)',
     'Asia/Bangkok': 'UTC+07:00 Indochina Time (Asia/Bangkok)',
     'Pacific/Niue': 'UTC-11:00 Niue Time (Pacific/Niue)',
     'Australia/Brisbane': 'UTC+10:00 Eastern Standard Time (Queensland) (Australia/Brisbane)',
     'America/Recife': 'UTC-03:00 Brasilia Time (America/Recife)',
     'MST': 'UTC-07:00 Mountain Standard Time (MST)',
     'Asia/Yerevan': 'UTC+04:00 Armenia Time (Asia/Yerevan)',
     'America/La_Paz': 'UTC-04:00 Bolivia Time (America/La_Paz)',
     'Poland': 'UTC+02:00 Central European Time (Poland)',
     'Asia/Urumqi': 'UTC+08:00 China Standard Time (Asia/Urumqi)',
     'Africa/Lusaka': 'UTC+02:00 Central African Time (Africa/Lusaka)',
     'US/Indiana-Starke': 'UTC-05:00 Central Standard Time (US/Indiana-Starke)',
     'Pacific/Guadalcanal': 'UTC+11:00 Solomon Is. Time (Pacific/Guadalcanal)',
     'America/Yellowknife': 'UTC-06:00 Mountain Standard Time (America/Yellowknife)',
     'Australia/LHI': 'UTC+10:30 Lord Howe Standard Time (Australia/LHI)',
     'Asia/Vientiane': 'UTC+07:00 Indochina Time (Asia/Vientiane)',
     'Asia/Kuwait': 'UTC+03:00 Arabia Standard Time (Asia/Kuwait)',
     'PLT': 'UTC+05:00 Pakistan Time (PLT)',
     'Africa/Conakry': 'UTC-00:00 Greenwich Mean Time (Africa/Conakry)',
     'America/Argentina/Tucuman': 'UTC-03:00 Argentine Time (America/Argentina/Tucuman)',
     'SystemV/CST6': 'UTC-06:00 Central Standard Time (SystemV/CST6)',
     'Europe/Oslo': 'UTC+02:00 Central European Time (Europe/Oslo)',
     'Australia/Currie': 'UTC+10:00 Eastern Standard Time (New South Wales) (Australia/Currie)',
     'America/St_Kitts': 'UTC-04:00 Atlantic Standard Time (America/St_Kitts)',
     'SystemV/EST5EDT': 'UTC-04:00 Eastern Standard Time (SystemV/EST5EDT)',
     'America/Panama': 'UTC-05:00 Eastern Standard Time (America/Panama)',
     'Africa/Gaborone': 'UTC+02:00 Central African Time (Africa/Gaborone)',
     'Asia/Hebron': 'UTC+03:00 Eastern European Time (Asia/Hebron)',
     'America/Guayaquil': 'UTC-05:00 Ecuador Time (America/Guayaquil)',
     'Asia/Kuala_Lumpur': 'UTC+08:00 Malaysia Time (Asia/Kuala_Lumpur)',
     'Europe/London': 'UTC+01:00 Greenwich Mean Time (Europe/London)',
     'America/Menominee': 'UTC-05:00 Central Standard Time (America/Menominee)',
     'Asia/Kamchatka': 'UTC+12:00 Petropavlovsk-Kamchatski Time (Asia/Kamchatka)',
     'Asia/Vladivostok': 'UTC+11:00 Vladivostok Time (Asia/Vladivostok)',
     'America/Matamoros': 'UTC-05:00 Central Standard Time (America/Matamoros)',
     'Brazil/DeNoronha': 'UTC-02:00 Fernando de Noronha Time (Brazil/DeNoronha)',
     'Asia/Qatar': 'UTC+03:00 Arabia Standard Time (Asia/Qatar)',
     'Israel': 'UTC+03:00 Israel Standard Time (Israel)',
     'NZ-CHAT': 'UTC+12:45 Chatham Standard Time (NZ-CHAT)',
     'Asia/Dubai': 'UTC+04:00 Gulf Standard Time (Asia/Dubai)',
     'Asia/Yakutsk': 'UTC+10:00 Yakutsk Time (Asia/Yakutsk)',
     'Asia/Omsk': 'UTC+07:00 Omsk Time (Asia/Omsk)',
     'Africa/Bangui': 'UTC+01:00 Western African Time (Africa/Bangui)',
     'NST': 'UTC+12:00 New Zealand Standard Time (NST)',
     'UTC': 'UTC-00:00 Coordinated Universal Time (UTC)',
     'SystemV/MST7': 'UTC-07:00 Mountain Standard Time (SystemV/MST7)',
     'America/Paramaribo': 'UTC-03:00 Suriname Time (America/Paramaribo)',
     'Etc/GMT-11': 'UTC+11:00 GMT+11:00 (Etc/GMT-11)',
     'Etc/GMT-10': 'UTC+10:00 GMT+10:00 (Etc/GMT-10)',
     'Africa/Lubumbashi': 'UTC+02:00 Central African Time (Africa/Lubumbashi)',
     'Etc/GMT-12': 'UTC+12:00 GMT+12:00 (Etc/GMT-12)',
     'Etc/GMT-14': 'UTC+14:00 GMT+14:00 (Etc/GMT-14)',
     'Pacific/Marquesas': 'UTC-09:30 Marquesas Time (Pacific/Marquesas)',
     'US/Central': 'UTC-05:00 Central Standard Time (US/Central)',
     'Europe/Bratislava': 'UTC+02:00 Central European Time (Europe/Bratislava)',
     'Asia/Anadyr': 'UTC+12:00 Anadyr Time (Asia/Anadyr)',
     'America/New_York': 'UTC-04:00 Eastern Standard Time (America/New_York)',
     'Pacific/Norfolk': 'UTC+11:30 Norfolk Time (Pacific/Norfolk)',
     'CST6CDT': 'UTC-05:00 Central Standard Time (CST6CDT)',
     'ART': 'UTC+03:00 Eastern European Time (ART)',
     'America/Dominica': 'UTC-04:00 Atlantic Standard Time (America/Dominica)',
     'Africa/Porto-Novo': 'UTC+01:00 Western African Time (Africa/Porto-Novo)',
     'Asia/Samarkand': 'UTC+05:00 Uzbekistan Time (Asia/Samarkand)',
     'Asia/Dushanbe': 'UTC+05:00 Tajikistan Time (Asia/Dushanbe)',
     'America/Kentucky/Louisville': 'UTC-04:00 Eastern Standard Time (America/Kentucky/Louisville)',
     'America/Toronto': 'UTC-04:00 Eastern Standard Time (America/Toronto)',
     'America/Bahia': 'UTC-03:00 Brasilia Time (America/Bahia)',
     'Indian/Maldives': 'UTC+05:00 Maldives Time (Indian/Maldives)',
     'Africa/Accra': 'UTC-00:00 Ghana Mean Time (Africa/Accra)',
     'Antarctica/South_Pole': 'UTC+12:00 New Zealand Standard Time (Antarctica/South_Pole)',
     'Asia/Muscat': 'UTC+04:00 Gulf Standard Time (Asia/Muscat)',
     'America/Virgin': 'UTC-04:00 Atlantic Standard Time (America/Virgin)',
     'America/Edmonton': 'UTC-06:00 Mountain Standard Time (America/Edmonton)',
     'Pacific/Wake': 'UTC+12:00 Wake Time (Pacific/Wake)',
     'America/Indiana/Tell_City': 'UTC-05:00 Central Standard Time (America/Indiana/Tell_City)',
     'Australia/Darwin': 'UTC+09:30 Central Standard Time (Northern Territory) (Australia/Darwin)',
     'America/Whitehorse': 'UTC-07:00 Pacific Standard Time (America/Whitehorse)',
     'America/Swift_Current': 'UTC-06:00 Central Standard Time (America/Swift_Current)',
     'Europe/Copenhagen': 'UTC+02:00 Central European Time (Europe/Copenhagen)',
     'America/Argentina/Salta': 'UTC-03:00 Argentine Time (America/Argentina/Salta)',
     'America/Montserrat': 'UTC-04:00 Atlantic Standard Time (America/Montserrat)',
     'Asia/Tashkent': 'UTC+05:00 Uzbekistan Time (Asia/Tashkent)',
     'Europe/Simferopol': 'UTC+04:00 Eastern European Time (Europe/Simferopol)',
     'Africa/Blantyre': 'UTC+02:00 Central African Time (Africa/Blantyre)',
     'America/Detroit': 'UTC-04:00 Eastern Standard Time (America/Detroit)',
     'America/Shiprock': 'UTC-06:00 Mountain Standard Time (America/Shiprock)',
     'America/Grenada': 'UTC-04:00 Atlantic Standard Time (America/Grenada)',
     'Atlantic/Faroe': 'UTC+01:00 Western European Time (Atlantic/Faroe)',
     'America/Indiana/Petersburg': 'UTC-04:00 Eastern Standard Time (America/Indiana/Petersburg)',
     'Asia/Kathmandu': 'UTC+05:45 Nepal Time (Asia/Kathmandu)',
     'Asia/Pontianak': 'UTC+07:00 West Indonesia Time (Asia/Pontianak)',
     'Jamaica': 'UTC-05:00 Eastern Standard Time (Jamaica)',
     'Europe/Athens': 'UTC+03:00 Eastern European Time (Europe/Athens)',
     'America/Port-au-Prince': 'UTC-04:00 Eastern Standard Time (America/Port-au-Prince)',
     'America/Cayman': 'UTC-05:00 Eastern Standard Time (America/Cayman)',
     'Etc/Universal': 'UTC-00:00 Coordinated Universal Time (Etc/Universal)',
     'Africa/Dar_es_Salaam': 'UTC+03:00 Eastern African Time (Africa/Dar_es_Salaam)',
     'America/Curacao': 'UTC-04:00 Atlantic Standard Time (America/Curacao)',
     'Indian/Kerguelen': 'UTC+05:00 French Southern & Antarctic Lands Time (Indian/Kerguelen)',
     'Africa/Khartoum': 'UTC+03:00 Eastern African Time (Africa/Khartoum)',
     'Asia/Manila': 'UTC+08:00 Philippines Time (Asia/Manila)',
     'Africa/Lome': 'UTC-00:00 Greenwich Mean Time (Africa/Lome)',
     'America/Jujuy': 'UTC-03:00 Argentine Time (America/Jujuy)',
     'Africa/Douala': 'UTC+01:00 Western African Time (Africa/Douala)',
     'EET': 'UTC+03:00 Eastern European Time (EET)',
     'CNT': 'UTC-02:30 Newfoundland Standard Time (CNT)',
     'America/Argentina/San_Juan': 'UTC-03:00 Argentine Time (America/Argentina/San_Juan)',
     'America/North_Dakota/New_Salem': 'UTC-05:00 Central Standard Time (America/North_Dakota/New_Salem)',
     'America/Kralendijk': 'UTC-04:00 Atlantic Standard Time (America/Kralendijk)',
     'Pacific/Port_Moresby': 'UTC+10:00 Papua New Guinea Time (Pacific/Port_Moresby)',
     'Europe/Jersey': 'UTC+01:00 Greenwich Mean Time (Europe/Jersey)',
     'Asia/Macao': 'UTC+08:00 China Standard Time (Asia/Macao)',
     'Europe/Andorra': 'UTC+02:00 Central European Time (Europe/Andorra)',
     'ROK': 'UTC+09:00 Korea Standard Time (ROK)',
     'Cuba': 'UTC-04:00 Cuba Standard Time (Cuba)',
     'Europe/Luxembourg': 'UTC+02:00 Central European Time (Europe/Luxembourg)',
     'Pacific/Honolulu': 'UTC-10:00 Hawaii Standard Time (Pacific/Honolulu)',
     'America/St_Thomas': 'UTC-04:00 Atlantic Standard Time (America/St_Thomas)',
     'SystemV/HST10': 'UTC-10:00 Hawaii Standard Time (SystemV/HST10)',
     'Pacific/Majuro': 'UTC+12:00 Marshall Islands Time (Pacific/Majuro)',
     'Asia/Hong_Kong': 'UTC+08:00 Hong Kong Time (Asia/Hong_Kong)',
     'Asia/Macau': 'UTC+08:00 China Standard Time (Asia/Macau)',
     'MST7MDT': 'UTC-06:00 Mountain Standard Time (MST7MDT)',
     'Europe/Belgrade': 'UTC+02:00 Central European Time (Europe/Belgrade)',
     'Asia/Choibalsan': 'UTC+08:00 Choibalsan Time (Asia/Choibalsan)',
     'US/Eastern': 'UTC-04:00 Eastern Standard Time (US/Eastern)',
     'Europe/Mariehamn': 'UTC+03:00 Eastern European Time (Europe/Mariehamn)',
     'Antarctica/McMurdo': 'UTC+12:00 New Zealand Standard Time (Antarctica/McMurdo)',
     'America/Thunder_Bay': 'UTC-04:00 Eastern Standard Time (America/Thunder_Bay)',
     'America/Los_Angeles': 'UTC-07:00 Pacific Standard Time (America/Los_Angeles)',
     'Asia/Kabul': 'UTC+04:30 Afghanistan Time (Asia/Kabul)',
     'Indian/Antananarivo': 'UTC+03:00 Eastern African Time (Indian/Antananarivo)',
     'Europe/Sarajevo': 'UTC+02:00 Central European Time (Europe/Sarajevo)',
     'Atlantic/Reykjavik': 'UTC-00:00 Greenwich Mean Time (Atlantic/Reykjavik)',
     'Asia/Nicosia': 'UTC+03:00 Eastern European Time (Asia/Nicosia)',
     'Etc/GMT+11': 'UTC-11:00 GMT-11:00 (Etc/GMT+11)',
     'Etc/GMT+10': 'UTC-10:00 GMT-10:00 (Etc/GMT+10)',
     'Pacific/Ponape': 'UTC+11:00 Pohnpei Time (Pacific/Ponape)',
     'Japan': 'UTC+09:00 Japan Standard Time (Japan)',
     'Asia/Ulan_Bator': 'UTC+08:00 Ulaanbaatar Time (Asia/Ulan_Bator)',
     'Kwajalein': 'UTC+12:00 Marshall Islands Time (Kwajalein)',
     'Pacific/Tongatapu': 'UTC+13:00 Tonga Time (Pacific/Tongatapu)',
     'America/Marigot': 'UTC-04:00 Atlantic Standard Time (America/Marigot)',
     'Pacific/Pitcairn': 'UTC-08:00 Pitcairn Standard Time (Pacific/Pitcairn)',
     'Pacific/Easter': 'UTC-06:00 Easter Is. Time (Pacific/Easter)',
     'SystemV/MST7MDT': 'UTC-06:00 Mountain Standard Time (SystemV/MST7MDT)',
     'US/East-Indiana': 'UTC-04:00 Eastern Standard Time (US/East-Indiana)',
     'Atlantic/South_Georgia': 'UTC-02:00 South Georgia Standard Time (Atlantic/South_Georgia)',
     'Africa/El_Aaiun': 'UTC+01:00 Western European Time (Africa/El_Aaiun)',
     'ACT': 'UTC+09:30 Central Standard Time (Northern Territory) (ACT)',
     'Chile/Continental': 'UTC-04:00 Chile Time (Chile/Continental)',
     'NET': 'UTC+04:00 Armenia Time (NET)',
     'America/Campo_Grande': 'UTC-04:00 Amazon Time (America/Campo_Grande)',
     'America/Dawson_Creek': 'UTC-07:00 Mountain Standard Time (America/Dawson_Creek)',
     'America/Rosario': 'UTC-03:00 Argentine Time (America/Rosario)',
     'Pacific/Galapagos': 'UTC-06:00 Galapagos Time (Pacific/Galapagos)',
     'Antarctica/Vostok': 'UTC+06:00 Vostok Time (Antarctica/Vostok)',
     'US/Aleutian': 'UTC-09:00 Hawaii-Aleutian Standard Time (US/Aleutian)',
     'Europe/Bucharest': 'UTC+03:00 Eastern European Time (Europe/Bucharest)',
     'America/Porto_Velho': 'UTC-04:00 Amazon Time (America/Porto_Velho)',
     'Europe/Monaco': 'UTC+02:00 Central European Time (Europe/Monaco)',
     'America/Indiana/Marengo': 'UTC-04:00 Eastern Standard Time (America/Indiana/Marengo)',
     'Africa/Ceuta': 'UTC+02:00 Central European Time (Africa/Ceuta)',
     'Europe/Rome': 'UTC+02:00 Central European Time (Europe/Rome)',
     'America/Winnipeg': 'UTC-05:00 Central Standard Time (America/Winnipeg)',
     'America/Knox_IN': 'UTC-05:00 Central Standard Time (America/Knox_IN)',
     'Asia/Aqtobe': 'UTC+05:00 Aqtobe Time (Asia/Aqtobe)',
     'Africa/Dakar': 'UTC-00:00 Greenwich Mean Time (Africa/Dakar)',
     'America/Fortaleza': 'UTC-03:00 Brasilia Time (America/Fortaleza)',
     'Pacific/Samoa': 'UTC-11:00 Samoa Standard Time (Pacific/Samoa)',
     'Pacific/Tarawa': 'UTC+12:00 Gilbert Is. Time (Pacific/Tarawa)',
     'America/Dawson': 'UTC-07:00 Pacific Standard Time (America/Dawson)',
     'Africa/Addis_Ababa': 'UTC+03:00 Eastern African Time (Africa/Addis_Ababa)',
     'Pacific/Efate': 'UTC+11:00 Vanuatu Time (Pacific/Efate)',
     'Pacific/Johnston': 'UTC-10:00 Hawaii Standard Time (Pacific/Johnston)',
     'GMT': 'UTC-00:00 Greenwich Mean Time (GMT)',
     'Canada/Yukon': 'UTC-07:00 Pacific Standard Time (Canada/Yukon)',
     'SystemV/YST9': 'UTC-09:00 Alaska Standard Time (SystemV/YST9)',
     'Asia/Qyzylorda': 'UTC+06:00 Qyzylorda Time (Asia/Qyzylorda)',
     'Europe/San_Marino': 'UTC+02:00 Central European Time (Europe/San_Marino)',
     'Asia/Jerusalem': 'UTC+03:00 Israel Standard Time (Asia/Jerusalem)',
     'MET': 'UTC+02:00 Middle Europe Time (MET)',
     'Pacific/Auckland': 'UTC+12:00 New Zealand Standard Time (Pacific/Auckland)',
     'SystemV/PST8': 'UTC-08:00 Pacific Standard Time (SystemV/PST8)',
     'America/Metlakatla': 'UTC-08:00 Metlakatla Standard Time (America/Metlakatla)',
     'Etc/Zulu': 'UTC-00:00 Coordinated Universal Time (Etc/Zulu)',
     'America/Denver': 'UTC-06:00 Mountain Standard Time (America/Denver)',
     'Indian/Chagos': 'UTC+06:00 Indian Ocean Territory Time (Indian/Chagos)',
     'America/Glace_Bay': 'UTC-03:00 Atlantic Standard Time (America/Glace_Bay)',
     'America/Hermosillo': 'UTC-07:00 Mountain Standard Time (America/Hermosillo)',
     'Africa/Tunis': 'UTC+01:00 Central European Time (Africa/Tunis)',
     'Etc/GMT-0': 'UTC-00:00 GMT+00:00 (Etc/GMT-0)',
     'Asia/Ust-Nera': 'UTC+11:00 Ust-Nera Time (Asia/Ust-Nera)',
     'Europe/Vaduz': 'UTC+02:00 Central European Time (Europe/Vaduz)',
     'America/Resolute': 'UTC-05:00 Central Standard Time (America/Resolute)',
     'Etc/GMT': 'UTC-00:00 GMT+00:00 (Etc/GMT)',
     'Asia/Gaza': 'UTC+03:00 Eastern European Time (Asia/Gaza)',
     'Europe/Dublin': 'UTC+01:00 Greenwich Mean Time (Europe/Dublin)',
     'US/Mountain': 'UTC-06:00 Mountain Standard Time (US/Mountain)',
     'Antarctica/DumontDUrville': "UTC+10:00 Dumont-d'Urville Time (Antarctica/DumontDUrville)",
     'America/Argentina/Catamarca': 'UTC-03:00 Argentine Time (America/Argentina/Catamarca)',
     'America/Indiana/Knox': 'UTC-05:00 Central Standard Time (America/Indiana/Knox)',
     'Europe/Nicosia': 'UTC+03:00 Eastern European Time (Europe/Nicosia)',
     'EAT': 'UTC+03:00 Eastern African Time (EAT)',
     'Africa/Timbuktu': 'UTC-00:00 Greenwich Mean Time (Africa/Timbuktu)',
     'Asia/Novosibirsk': 'UTC+07:00 Novosibirsk Time (Asia/Novosibirsk)',
     'EST': 'UTC-05:00 Eastern Standard Time (EST)',
     'Mexico/BajaNorte': 'UTC-07:00 Pacific Standard Time (Mexico/BajaNorte)',
     'Africa/Kigali': 'UTC+02:00 Central African Time (Africa/Kigali)',
     'Brazil/West': 'UTC-04:00 Amazon Time (Brazil/West)',
     'America/Grand_Turk': 'UTC-04:00 Eastern Standard Time (America/Grand_Turk)',
     'IET': 'UTC-04:00 Eastern Standard Time (IET)',
     'Mexico/BajaSur': 'UTC-06:00 Mountain Standard Time (Mexico/BajaSur)',
     'Canada/Central': 'UTC-05:00 Central Standard Time (Canada/Central)',
     'Africa/Lagos': 'UTC+01:00 Western African Time (Africa/Lagos)',
     'Europe/Sofia': 'UTC+03:00 Eastern European Time (Europe/Sofia)',
     'VST': 'UTC+07:00 Indochina Time (VST)',
     'Singapore': 'UTC+08:00 Singapore Time (Singapore)',
     'Africa/Tripoli': 'UTC+02:00 Eastern European Time (Africa/Tripoli)',
     'America/Anchorage': 'UTC-08:00 Alaska Standard Time (America/Anchorage)',
     'Pacific/Nauru': 'UTC+12:00 Nauru Time (Pacific/Nauru)'
 }
 var timezones; 
 $(document).ready(function(){
 	t = '<select id="timezone">';
 	$.each(times,function (key,val) {
 	t += '<option value="'+key+'">'+val+'</option>'
 	})
 	t += '</select>';
 	timezones = t
 });