docker push estebanf/intalio_dev
docker push estebanf/ibpms_and_archive
docker push estebanf/archive_light
docker push estebanf/alpine_java
docker push estebanf/ibpms_ha_server
docker push estebanf/ibpms_ha_mysql
docker push estebanf/ibpms_ha_balancer
docker push estebanf/florida_blue_pg
docker push estebanf/ibpms_ha_files
docker push estebanf/everteam
docker push estebanf/case_demo_intalio
docker push estebanf/base_java
docker push estebanf/case_demo_db
docker push estebanf/case_demo_everteam
docker push estebanf/case_demo_webapp
docker push estebanf/case_demo_nginx
docker push estebanf/case_demo_solr
docker push estebanf/case_demo_zookeeper
docker push estebanf/alpine_tomcat
