<?xml version='1.0' encoding='utf-8'?>
<wsdl:definitions xmlns:diag="http://floridabluedemo.com/Processes/CreateMember" xmlns:Caller="http://floridabluedemo.com/Processes/CreateMember/Caller" xmlns:Process="http://floridabluedemo.com/Processes/CreateMember/Process" xmlns:ProcessimplicitPartner="http://floridabluedemo.com/Processes/CreateMember/ProcessimplicitPartner" xmlns:tns="http://www.example.org/Demo" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:pnlk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:bpdm="http://www.intalio/designer/business-process-data-modeling" targetNamespace="http://floridabluedemo.com/Processes/CreateMember">
    <wsdl:import namespace="http://floridabluedemo.com/Processes/CreateMember/Process" location="CreateMember-Process.wsdl"/>
    <wsdl:import namespace="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice" location="../Connectors/Database/insert_member.sql/insert_member.sql.wsdl"/>
    <pnlk:partnerLinkType name="CallerAndProcess">
        <pnlk:role name="Process_for_Caller" portType="Process:ForCaller"/>
    </pnlk:partnerLinkType>
    <pnlk:partnerLinkType name="ProcessimplicitPartnerAndProcessForInsert_memberPortPlk">
        <pnlk:role name="ProcessimplicitPartner_for_Process" portType="ns:insert_memberPort"/>
    </pnlk:partnerLinkType>
</wsdl:definitions>