/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-05-04 10:41:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(' ');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"/everteam/ET_icon.ico\" type=\"image/x-icon\"/>\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=10\"/>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<title>Login Page - Everteam.iBPMS</title>\n");
      out.write("\n");
      out.write("\t\t<meta name=\"description\" content=\"User login page\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("\n");
      out.write("\t\t<!--basic styles-->\n");
      out.write("\n");
      out.write("\t\t<link href=\"style/plugin/bootstrap.min.css\" rel=\"stylesheet\" />\n");
      out.write("\t\t<link href=\"style/plugin/bootstrap-responsive.min.css\" rel=\"stylesheet\" />\n");
      out.write("\t\t<link href=\"style/plugin/font-awesome.min.css\" rel=\"stylesheet\"/>\n");
      out.write("\t\t<!--[if IE]>\n");
      out.write("\t\t<link href=\"style/custom/common-ie.css?version=2676\" rel=\"stylesheet\" />\n");
      out.write("\t\t<![endif]-->\n");
      out.write("\t\t<!--[if IE 7]>\n");
      out.write("\t\t  <link rel=\"stylesheet\" href=\"css/font-awesome-ie7.min.css\" />\n");
      out.write("\t\t<![endif]-->\n");
      out.write("\n");
      out.write("\t\t<!--page specific plugin styles-->\n");
      out.write("\n");
      out.write("\t\t<!--fonts-->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"style/plugin/google-fonts.css\" />\n");
      out.write("\t\t<!--ace styles-->\n");
      out.write("\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"style/plugin/ace.min.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"style/plugin/ace-responsive.min.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"style/custom/login.css\" />\n");
      out.write("\n");
      out.write("\t\t<!--[if lt IE 9]>\n");
      out.write("\t\t  <link rel=\"stylesheet\" href=\"css/ace-ie.min.css\" />\n");
      out.write("\t\t<![endif]-->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"style/custom/common.css?version=2676\" />\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/plugin/jquery-1.9.1.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/plugin/jquery.jcryption.js\"></script>\n");
      out.write("\t\t<style type=\"text/css\">\n");
      out.write("\t\t.login-layout .widget-box .widget-main {\n");
      out.write("\t\t\tborder-radius: 20px;\n");
      out.write("\t\t}\n");
      out.write("\t\t.widget-body {\n");
      out.write("\t\t\tborder-radius: 20px;\n");
      out.write("\t\t}\n");
      out.write("\t\t@font-face {\n");
      out.write("\t\t\tfont-family: \"SegoeUI\";\n");
      out.write("\t\t\tsrc: url('style/custom/fonts/segoeui.ttf') format(\"truetype\");\n");
      out.write("\t\t}\n");
      out.write("\t\t</style>\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\tif($(\"#main-content\").find('.login-container').length==parseInt(1))\n");
      out.write("\t\t\twindow.location = \"/intalio\";\n");
      out.write("\t\tvar check =0;\n");
      out.write("\t\tvar is_ie8 = false;\n");
      out.write("\tvar shake_box = function (id) \n");
      out.write("\t{\n");
      out.write("\t\tif (is_ie8){\n");
      out.write("\t\t\t$('#loginError').removeClass('hide');\n");
      out.write("\t\t\tif($('.userNameError').text().length !=0)\n");
      out.write("\t\t\t\t$('#loginError').text($('.userNameError').text())\n");
      out.write("\t\t\telse if($('.passwordError').text().length !=0)\n");
      out.write("\t\t\t\t$('#loginError').text($('.passwordError').text())\n");
      out.write("\t\t\telse if($('.combinationError').text().length !=0)\n");
      out.write("\t\t\t\t$('#loginError').text($('.combinationError').text())\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\tvar duration = 1000;\n");
      out.write("\t\t\tvar stepcount = 0;\n");
      out.write("\t\t\t$('#username').select();\n");
      out.write("\t\t\tfunction setTransform(el, transform) \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tvar bstyles = [\"-webkit-transform\", \"-moz-transform\", \"-ms-transform\", \"transform\"];\n");
      out.write("\t\t\t\tfor(var i in bstyles) {\n");
      out.write("\t\t\t\t\t\tel.css(bstyles[i], transform);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tfunction quiver(el, x) \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tdeg = 0;\n");
      out.write("\t\t\t\tif (x != 0) \n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\tdeg = Math.cos(x * duration / 100) / (x / duration * 100);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\tsetTransform(el, \"rotate(\" + deg + \"deg)\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$(\"#login-box\").animate(\n");
      out.write("\t\t\t\t\t\t// pick any unsused but iterable animation property, so the step function is triggered\n");
      out.write("\t\t\t\t\t\t{ opacity: '1' },\n");
      out.write("\t\t\t\t\t\t{duration: duration,\n");
      out.write("\t\t\t\t\t\tstep: function(now, fx) \n");
      out.write("\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t//increment the function input\n");
      out.write("\t\t\t\t\t\t\tstepcount += 1;\n");
      out.write("\t\t\t\t\t\t\tquiver($(\"#login-box\"), stepcount);\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\tcomplete: function() {\n");
      out.write("\t\t\t\t\t\t\t//reset the rotation\n");
      out.write("\t\t\t\t\t\t\tquiver($(\"#login-box\"), 0);\n");
      out.write("\t\t\t\t\t\t\tsetTransform($(\"#login-box\"), \"\");\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t);\n");
      out.write("\t\t}\n");
      out.write("\t\tcheck =3;\n");
      out.write("\t};\n");
      out.write("\tvar unSupportedKeyCodes = [34,39,42,58,59,60,61,62,63,124];\n");
      out.write("\t\n");
      out.write("\tfunction validateLoginFields(event) {\n");
      out.write("\t\tvar key = event.keyCode || event.which;\n");
      out.write("\t\tif ($.inArray(key,unSupportedKeyCodes)>=0) {\n");
      out.write("\t\t\tevent.preventDefault();\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}else if(key == 13)\n");
      out.write("\t\t\thandleSubmit();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction validateOnPaste(obj){\n");
      out.write("\t\tvar element = obj;\n");
      out.write("\t\tsetTimeout(function(){\n");
      out.write("\t\t\tvar textboxValue = $(element).val();\n");
      out.write("\t\t\t$(element).val(\"\");\n");
      out.write("\t\t\t$(element).val(textboxValue.replace(/[<>?=\"';:]/g, ''));\n");
      out.write("\t\t},100);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar rand = function() {\n");
      out.write("\t\treturn Math.random().toString(36).substr(2);\n");
      out.write("\t};\n");
      out.write("\n");
      out.write("\tfunction handleSubmit(){\n");
      out.write("\t\tvar generateString = rand()+$('#username').val()+rand()+$(\"#password\").val()+rand();\n");
      out.write("\t\tvar hashObj \t  = new jsSHA(generateString,\"ASCII\");\n");
      out.write("\t\tvar encrypted_key = hashObj.getHash(\"SHA-512\", \"HEX\");\n");
      out.write("\t\t$.jCryption.authenticate(encrypted_key, \"encrypt?generateKeyPair=true\", \"encrypt?handshake=true\",\n");
      out.write("\t\t\tfunction(AESKey) {\n");
      out.write("\t\t\t\tif($(\"#password\").val()!=\"\"){\n");
      out.write("\t\t\t\t\tvar encryptedString = $.jCryption.encrypt($(\"#password\").val(), encrypted_key);\n");
      out.write("\t\t\t\t\t$(\"#password\").val(encryptedString);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t$(\"#form\").submit();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction validatePassword(event){\n");
      out.write("\t\tvar key = event.keyCode || event.which;\n");
      out.write("\t\tif(key == 13)\n");
      out.write("\t\t\thandleSubmit();\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\t<!--[if IE 8]>\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\tis_ie8 = true\n");
      out.write("\t\t\t</script>\n");
      out.write("\t<![endif]-->\n");
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body class=\"login-layout\"  style=\"font-family:SegoeUI;\">\n");
      out.write("\t\t<div class=\"container-fluid\" id=\"main-container\">\n");
      out.write("\t\t\t<div id=\"main-content\">\n");
      out.write("\t\t\t\t<div class=\"row-fluid\">\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"login-container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"position-relative\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"login-box\" class=\"visible widget-box no-border\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"widget-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-main\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"io-login-box-logo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/everteam-login.png\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space-6\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<form action=\"login.htm\" id=\"form\" autocomplete=\"off\" class=\"login-form\" method=\"POST\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <input type=\"hidden\" id=\"actionName\" name=\"actionName\" value=\"logIn\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <span class=\"hide text-danger\" id=\"loginError\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"block clearfix\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"block input-icon input-icon-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f0 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      _jspx_th_spring_005fbind_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fbind_005f0.setParent(null);
      // /WEB-INF/jsp/login.jsp(195,15) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fbind_005f0.setPath("login.username");
      int[] _jspx_push_body_count_spring_005fbind_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fbind_005f0 = _jspx_th_spring_005fbind_005f0.doStartTag();
        if (_jspx_eval_spring_005fbind_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          org.springframework.web.servlet.support.BindStatus status = null;
          status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-sm-12 input username\" placeholder=\"Username\" tabindex=\"1\" name=\"username\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" id=\"username\" autocomplete=\"off\" onkeypress='javascript:validateLoginFields(event)' onpaste='javascript:validateOnPaste(this)'/>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"hide userNameError\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</span>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_spring_005fbind_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fbind_005f0))
              return;
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_spring_005fbind_005f0.doAfterBody();
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005fbind_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fbind_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fbind_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fbind_005f0.doFinally();
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f0);
      }
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"block clearfix\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"block input-icon input-icon-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f1 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      _jspx_th_spring_005fbind_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fbind_005f1.setParent(null);
      // /WEB-INF/jsp/login.jsp(208,15) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fbind_005f1.setPath("login.password");
      int[] _jspx_push_body_count_spring_005fbind_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fbind_005f1 = _jspx_th_spring_005fbind_005f1.doStartTag();
        if (_jspx_eval_spring_005fbind_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          org.springframework.web.servlet.support.BindStatus status = null;
          status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"col-sm-12 input password\" placeholder=\"Password\" id=\"password\" tabindex=\"2\" name=\"password\" value=\"\" autocomplete=\"off\" onkeypress='javascript:validatePassword(event)'/>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"hide passwordError\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</span>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_spring_005fbind_005f1, _jspx_page_context, _jspx_push_body_count_spring_005fbind_005f1))
              return;
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_spring_005fbind_005f1.doAfterBody();
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005fbind_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fbind_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fbind_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fbind_005f1.doFinally();
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f1);
      }
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f2 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      _jspx_th_spring_005fbind_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fbind_005f2.setParent(null);
      // /WEB-INF/jsp/login.jsp(220,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fbind_005f2.setPath("login");
      int[] _jspx_push_body_count_spring_005fbind_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fbind_005f2 = _jspx_th_spring_005fbind_005f2.doStartTag();
        if (_jspx_eval_spring_005fbind_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          org.springframework.web.servlet.support.BindStatus status = null;
          status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fforEach_005f0(_jspx_th_spring_005fbind_005f2, _jspx_page_context, _jspx_push_body_count_spring_005fbind_005f2))
              return;
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_spring_005fbind_005f2.doAfterBody();
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005fbind_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fbind_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fbind_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fbind_005f2.doFinally();
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f2);
      }
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type='button' onclick='javascript:handleSubmit()'tabindex=\"3\" class=\"col-sm-4 btn btn-sm btn-primary pull-right\" id=\"log_in_btn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon-key\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div><!--/widget-main-->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div><!--/widget-body-->\n");
      out.write("\t\t\t\t\t\t\t\t\t</div><!--/login-box-->\n");
      out.write("\t\t\t\t\t\t\t\t</div><!--/position-relative-->\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div><!--/span-->\n");
      out.write("\t\t\t\t</div><!--/row-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div><!--/.fluid-container-->\n");
      out.write("\n");
      out.write("\t\t<!--basic scripts-->\n");
      out.write("\n");
      out.write(" \n");
      out.write("\t\t<!--page specific plugin scripts-->\n");
      out.write("\n");
      out.write("\t\t<!--inline scripts related to this page-->\n");
      out.write("\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(document).ready(function(){\n");
      out.write("\t\t\t$.ajaxSetup({ cache: false });\n");
      out.write("\t\t\t$('#username').focus();\n");
      out.write("\t\t\t$('#username').select();\n");
      out.write("\t\t});\n");
      out.write("\t\t\tfunction show_box(id) {\n");
      out.write("\t\t\t $('.widget-box.visible').removeClass('visible');\n");
      out.write("\t\t\t $('#'+id).addClass('visible');\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$('.login-container').css('margin-top',($(window).height()-360)/2);\n");
      out.write("\t\t\t$('.login-container').css('margin-left',($(window).width()-360)/2);\n");
      out.write("\t\t</script>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fbind_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fbind_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fbind_005f0);
    // /WEB-INF/jsp/login.jsp(198,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty status.errorMessage}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tshake_box();\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</script>\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fbind_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fbind_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fbind_005f1);
    // /WEB-INF/jsp/login.jsp(211,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty status.errorMessage}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tshake_box();\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</script>\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fbind_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fbind_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fbind_005f2);
    // /WEB-INF/jsp/login.jsp(221,16) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.errorMessages}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/jsp/login.jsp(221,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("errorMessage");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"hide combinationError\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tshake_box();\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</script>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent(null);
    // /WEB-INF/jsp/login.jsp(233,16) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("com_intalio_bpms_console_login_loginBtn");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }
}
