version: '2'
services:
  et_zookeeper:
    image: estebanf/case_demo_zookeeper
    container_name: et_zookeeper
  et_solr:
    image: estebanf/case_demo_solr
    container_name: et_solr
    environment:
      ZOO: et_zookeeper
    links:
      - et_zookeeper
    depends_on:
      - et_zookeeper
  et_webapp:
    image: estebanf/everteam
    container_name: et_webapp
    ports:
      - "8080:8080"
    extra_hosts:
      - "everteam.local:127.0.0.1"
    links:
      - et_zookeeper
    depends_on:
      - et_zookeeper
