<wsdl:definitions targetNamespace="urn:intalio.com:connectors:database:budgeting:select_project_attachmentsservice" xmlns:tns="urn:intalio.com:connectors:database:budgeting:select_project_attachmentsservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:intalio.com:connectors:database:budgeting:select_project_attachmentsservice">
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="select_project_attachments.xsd" namespace="urn:intalio.com:connectors:database:budgeting:select_project_attachmentsservice"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="select_project_attachmentsInput">
        <wsdl:part name="parameters" element="ns:select_project_attachmentsParameterSet"/>
    </wsdl:message>
    <wsdl:message name="select_project_attachmentsOutput">
        <wsdl:part name="parameters" element="ns:select_project_attachmentsResultSet"/>
    </wsdl:message>
    <wsdl:message name="select_project_attachmentsFault">
        <wsdl:part name="fault" element="ns:select_project_attachmentsFault"/>
    </wsdl:message>
    <wsdl:portType name="select_project_attachmentsPort">
        <wsdl:operation name="select_project_attachments">
            <wsdl:input message="tns:select_project_attachmentsInput"/>
            <wsdl:output message="tns:select_project_attachmentsOutput"/>
            <wsdl:fault message="tns:select_project_attachmentsFault" name="nsselect_project_attachmentsFault"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="select_project_attachmentsPortSoapBinding" type="tns:select_project_attachmentsPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="select_project_attachments">
            <soap:operation style="document" soapAction="urn:intalio:connector:jdbc:query:select_project_attachments"/>
            <wsdl:input>
                <soap:body namespace="urn:intalio.com:connectors:database:budgeting:select_project_attachmentsservice" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="urn:intalio.com:connectors:database:budgeting:select_project_attachmentsservice" use="literal"/>
            </wsdl:output>
            <wsdl:fault name="nsselect_project_attachmentsFault">
                <soap:body namespace="urn:intalio.com:connectors:database:budgeting:select_project_attachmentsservice" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="select_project_attachmentsService">
        <wsdl:port binding="tns:select_project_attachmentsPortSoapBinding" name="select_project_attachmentsPort">
            <soap:address location="http://bpms.local:8080/everteam/ode/processes/Budgeting/Connectors/Database/select_project_attachments"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>