<wsdl:definitions targetNamespace="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice" xmlns:tns="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice">
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="insert_member.xsd" namespace="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="insert_memberInput">
        <wsdl:part name="parameters" element="ns:insert_memberParameterSet"/>
    </wsdl:message>
    <wsdl:message name="insert_memberOutput">
        <wsdl:part name="parameters" element="ns:insert_memberResultSet"/>
    </wsdl:message>
    <wsdl:message name="insert_memberFault">
        <wsdl:part name="fault" element="ns:insert_memberFault"/>
    </wsdl:message>
    <wsdl:portType name="insert_memberPort">
        <wsdl:operation name="insert_member">
            <wsdl:input message="tns:insert_memberInput"/>
            <wsdl:output message="tns:insert_memberOutput"/>
            <wsdl:fault message="tns:insert_memberFault" name="nsinsert_memberFault"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="insert_memberPortSoapBinding" type="tns:insert_memberPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="insert_member">
            <soap:operation style="document" soapAction="urn:intalio:connector:jdbc:query:insert_member"/>
            <wsdl:input>
                <soap:body namespace="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice" use="literal"/>
            </wsdl:output>
            <wsdl:fault name="nsinsert_memberFault">
                <soap:body namespace="urn:intalio.com:connectors:database:floridabluedemo:insert_memberservice" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="insert_memberService">
        <wsdl:port binding="tns:insert_memberPortSoapBinding" name="insert_memberPort">
            <soap:address location="http://bpms.local:8080/everteam/ode/processes/FloridaBlueDemo/Connectors/Database/insert_member"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>