<?xml version='1.0' encoding='utf-8'?>
<wsdl:definitions xmlns:ns="urn:intalio.com:connectors:database:testxsd:getpeopleservice" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Pool1="http://testxsd.com/testXsd/Pool1" xmlns:Pool="http://testxsd.com/testXsd/Pool" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:GetData="http://www.example.org/MoveData" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:diag="http://testxsd.com/testXsd" xmlns:tns="http://www.example.org/message" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:pnlk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:this="http://testxsd.com/testXsd/Pool0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://testxsd.com/testXsd/Pool0">
    <wsdl:types>
        <xs:schema targetNamespace="http://www.example.org/MoveData">
            <xs:include schemaLocation="GetData.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="EventStartMessageRequest">
        <wsdl:part name="body" element="GetData:MoveDataRequest"/>
    </wsdl:message>
    <wsdl:message name="EventStartMessageResponse">
        <wsdl:part name="body" element="GetData:MoveDataResponse"/>
    </wsdl:message>
    <wsdl:portType name="ForPool">
        <wsdl:operation name="EventStartMessage">
            <wsdl:input message="this:EventStartMessageRequest" name="EventStartMessage"/>
            <wsdl:output message="this:EventStartMessageResponse" name="EventStartMessageResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CanonicBindingForPool" type="this:ForPool">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="EventStartMessage">
            <soap:operation style="document" soapAction="http://testxsd.com/testXsd/Pool0/ForPool/EventStartMessage"/>
            <wsdl:input name="EventStartMessage">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="EventStartMessageResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CanonicServiceForPool">
        <wsdl:port name="canonicPort" binding="this:CanonicBindingForPool">
            <soap:address location="http://192.168.1.85:8080/intalio/ode/processes/testXSD/testXsd/Pool0/Pool"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>