/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-05-04 10:49:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.widgets.processes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class average_005fcompletion_005ftime_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var packageListDashboard = {};\n");
      out.write("/** AVG in this Script refers to Average Completion Time */\n");
      out.write("/** @Function Name   : Jquery Ready Function \n");
      out.write(" *   @Description     : jquery ready function\n");
      out.write(" *   @param           :\n");
      out.write(" *   @returns         :\n");
      out.write(" * */\n");
      out.write("$(function () {\n");
      out.write("    var widgetStateId = $('#average_completion_time').closest('.widget').attr(\"id\");\n");
      out.write("    var widgetObject = getWidgetObject(widgetStateId);\n");
      out.write("    if (widgetObject.filter == undefined || widgetObject.filter == null || widgetObject.filter ==''){\n");
      out.write("        var filterObject = {};\n");
      out.write("        filterObject.chartType = defaults.swf3;\n");
      out.write("        widgetObject.filter = filterObject;\n");
      out.write("        persistWidget(widgetObject);\n");
      out.write("    }\n");
      out.write("    var divId_AVG = defaults.chart1 + widgetStateId;\n");
      out.write("    $('#average_completion_time').attr('id', divId_AVG);\n");
      out.write("    $('#avgChartFilter').attr('id', \"avgChartFilter\"+widgetStateId);\n");
      out.write("    /**all possible charts*/\n");
      out.write("    var possibleCharts = [defaults.swf3, defaults.swf4, defaults.swf5, defaults.swf7, defaults.swf8, defaults.swf9,defaults.swf13];\n");
      out.write("    var possibleChartsNames = [\"Column chart 3D\", \"Pie chart 3D\", \"Doughnut chart 3D\",\"Column chart 2D\", \"Pie chart 2D\", \"Doughnut chart 2D\",\"Bar chart\"];\n");
      out.write("    $('#avgChartFilter'+widgetStateId+' .chartTypes').empty();\n");
      out.write("    $.each(possibleCharts, function (idx, value) {\n");
      out.write("        $('#avgChartFilter'+widgetStateId+' .chartTypes').append('<option value=\"'+value+'\">'+possibleChartsNames[idx]+'</option>');\n");
      out.write("    });\n");
      out.write("    $('#avgChartFilter'+widgetStateId+' .chartTypes').chosen();\n");
      out.write("    $('#avgChartFilter'+widgetStateId+' .chartTypes').next().css('width',170);\n");
      out.write("    var filterIcon = \"&nbsp;<a href='#' class='filterIcon' onclick='filterProcessAVGChart(this);'><i title='Filter Chart' class='fa fa-cog'></i></a>\";\n");
      out.write("    var refreshIcon = \"<a onclick=getAVGCompData(this); class='refreshChart' data-action='reload'><i title='Refresh' class='fa fa-refresh'></i></a>\";\n");
      out.write("    if ($(\"#\" + divId_AVG).closest('.widget-box').find('.widget-toolbar').find('.filterIcon').length == 0) {\n");
      out.write("        $(\"#\" + divId_AVG).closest('.widget-box').find('.widget-toolbar').children(':nth-child(2)').replaceWith(refreshIcon);\n");
      out.write("        $(\"#\" + divId_AVG).closest('.widget-box').find('.widget-toolbar').prepend(filterIcon);\n");
      out.write("    }\n");
      out.write("    getAVGCompData($(\"#\" + divId_AVG),widgetStateId);\n");
      out.write("    $('.chartFilterDates').datepicker({autoclose:true}).next().on(ace.click_event, function(){ $(this).prev().focus(); });\n");
      out.write("    $('#avgChartFilter'+widgetStateId+' .fromDate').on('change',function() {\n");
      out.write("\t\tvar fromDate = $('#avgChartFilter'+widgetStateId+' .fromDate').val();\n");
      out.write("\t\tvar toDate = $('#avgChartFilter'+widgetStateId+' .toDate').val();\n");
      out.write("\t\tif(fromDate > toDate)\n");
      out.write("\t\t\t$('#avgChartFilter'+widgetStateId+' .toDate').val(\"\");\n");
      out.write("\t\t$('#avgChartFilter'+widgetStateId+' .toDate').datepicker('setStartDate',fromDate);\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("\n");
      out.write("/** @Function Name   : getAVGCompData\n");
      out.write(" *   @Description     : fetches the data from server\n");
      out.write(" *   @param           : query fetch / refresh\n");
      out.write(" *   @returns         :\n");
      out.write(" * */\n");
      out.write("\n");
      out.write("function getAVGCompData(obj,widId) {\n");
      out.write("\tclickRefresh(obj,true);\n");
      out.write("    var widgetStateId;\n");
      out.write("    var data = {};\n");
      out.write("    if ($(obj).length != 0){\n");
      out.write("        widgetStateId = $(obj).closest('.widget').attr(\"id\");\n");
      out.write("    } else if (widId != null && widId != undefined){\n");
      out.write("        widgetStateId = widId;\n");
      out.write("    }\n");
      out.write("    var widgetObject = getWidgetObject(widgetStateId);\n");
      out.write("    if (widgetObject != null && widgetObject.filter != undefined && widgetObject.filter.process!=undefined && widgetObject.filter != ''){\n");
      out.write("        var filterObject = widgetObject.filter;\n");
      out.write("        if (filterObject.fromDate != undefined && filterObject.fromDate != null)\n");
      out.write("            data.since = filterObject.fromDate\n");
      out.write("        if (filterObject.toDate != undefined && filterObject.toDate != null)\n");
      out.write("            data.until = filterObject.toDate\n");
      out.write("        if (filterObject.process != undefined && filterObject.process != null)\n");
      out.write("            data.process = filterObject.process\n");
      out.write("        if(filterObject.activeProcess)\n");
      out.write("            data.activeOnly = filterObject.activeProcess;\n");
      out.write("        else\n");
      out.write("            data.activeOnly = false;\n");
      out.write("        sendAjaxCall('dashboard/widgets/processAverageCompletionTime', \"POST\", false, true, \"json\", data, avgComErrorCall, function(responseData){\n");
      out.write("            clickRefresh(obj,false);\n");
      out.write("\t\t\t\tif(responseData.error_message == undefined)\n");
      out.write("\t\t\t\t\tpopulateAvgCompTimeData(responseData,widgetStateId);\n");
      out.write("\t\t\t\telse\n");
      out.write("\t\t\t\t\tshowErrorNotification(responseData.error_message);\n");
      out.write("\t\t});\n");
      out.write("    }else\n");
      out.write("\t\tfilterProcessAVGChart($('#'+widId).find('.filterIcon'));\n");
      out.write("}\n");
      out.write("\n");
      out.write("function filterProcessAVGChart(obj){\n");
      out.write("    var widgetStateId = $(obj).closest('.widget').attr(\"id\");\n");
      out.write("    var widgetObject = getWidgetObject(widgetStateId);\n");
      out.write("    var modalObj = $('#avgChartFilter'+widgetStateId);\n");
      out.write("    addLoading($(modalObj).find('.modal-body'));\n");
      out.write("    $('#loading').css('margin-top',30);\n");
      out.write("    $(modalObj).find('.chartFilterTable .error-Msg').addClass('hide');\n");
      out.write("    modalShow('avgChartFilter'+widgetStateId);\n");
      out.write("    var data = {}; \n");
      out.write("    sendAjaxCall('dashboard/filters/processes', \"POST\", false, true, \"json\", data, avgComErrorCall, function(responseData){\n");
      out.write("        if(responseData.error_message == undefined){\n");
      out.write("            avgProcessFilter = responseData.process;\n");
      out.write("            populateAVGFilterData(responseData,widgetStateId);\n");
      out.write("        }\n");
      out.write("        else\n");
      out.write("            showErrorNotification(responseData.error_message);\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function populateAVGFilterData(data,widgetStateId){\n");
      out.write("    var widgetObject = getWidgetObject(widgetStateId);\n");
      out.write("    var modalObj = $('#avgChartFilter'+widgetStateId);\n");
      out.write("    var chartObj = $(modalObj).find('.chartTypes');\n");
      out.write("    if (widgetObject != null && widgetObject.filter != undefined && widgetObject.filter != null && widgetObject.filter != ''){\n");
      out.write("        var filterObject = widgetObject.filter;\n");
      out.write("        activeObj = $(modalObj).find('.AVGActiveProc');\n");
      out.write("        if(filterObject.activeProcess)\n");
      out.write("            activeObj.prop('checked',filterObject.activeProcess);\n");
      out.write("        else\n");
      out.write("            activeObj.prop('checked',false);\n");
      out.write("        updateAVGPackages(activeObj);\n");
      out.write("        if (filterObject.fromDate != undefined && filterObject.fromDate != null){\n");
      out.write("            $(modalObj).find('.fromDate').val(filterObject.fromDate);\n");
      out.write("            $('#avgChartFilter'+widgetStateId+' .toDate').datepicker('setStartDate',filterObject.fromDate);\n");
      out.write("\t\t}\n");
      out.write("        else \n");
      out.write("            $(modalObj).find('.fromDate').val('');\n");
      out.write("        if (filterObject.toDate != undefined && filterObject.toDate != null)\n");
      out.write("            $(modalObj).find('.toDate').val(filterObject.toDate);\n");
      out.write("        else \n");
      out.write("            $(modalObj).find('.toDate').val('');\n");
      out.write("        if (filterObject.chartType != undefined && filterObject.chartType != null){\n");
      out.write("            chartObj.next().remove();\n");
      out.write("            chartObj.removeAttr('style').removeClass('chzn-done');\n");
      out.write("            chartObj.val(filterObject.chartType);\n");
      out.write("            chartObj.chosen();\n");
      out.write("            chartObj.next().css('width',170);\n");
      out.write("        }\n");
      out.write("    } \n");
      out.write("    if(widgetObject != null) {\n");
      out.write("        if (widgetObject.title != undefined && widgetObject.title != null)\n");
      out.write("            $(modalObj).find('.chartName').val(widgetObject.title);\n");
      out.write("    }\n");
      out.write("    removeLoading($(modalObj).find('.modal-body'));\n");
      out.write("    $(modalObj).find('.modal-footer .applyButton').attr('widgetId',widgetStateId);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function updateAVGPackages(obj){\n");
      out.write("    var prevPackage,changedPackage=[];\n");
      out.write("    var widgetStateId = $(obj).closest('.widget').attr(\"id\");\n");
      out.write("    var modalObj = $('#avgChartFilter'+widgetStateId);\n");
      out.write("    avgPackageObj = $(modalObj).find('.AVGPackageList');\n");
      out.write("    avgProcessObj = $(modalObj).find('.AVGProcessesList');\n");
      out.write("    \n");
      out.write("    avgPackageObj.removeAttr('style').removeClass('chzn-done');\n");
      out.write("    avgProcessObj.removeAttr('style').removeClass('chzn-done');\n");
      out.write("    avgProcessObj.next().remove();\n");
      out.write("    avgPackageObj.next().remove();\n");
      out.write("    \n");
      out.write("    avgProcessObj.closest('tr').addClass('hide');\n");
      out.write("    avgPackageObj.empty();\n");
      out.write("    packageListDashboard = {};\n");
      out.write("    var widgetObject = getWidgetObject(widgetStateId);\n");
      out.write("    var filterObject = widgetObject.filter;\n");
      out.write("    $.each(avgProcessFilter,function(key,value){\n");
      out.write("       if(value.package){\n");
      out.write("            if(($(obj).prop('checked') && value.status===\"ACTIVE\") || !$(obj).prop('checked')) {\n");
      out.write("                prevPackage = value.id;\n");
      out.write("                packageListDashboard[prevPackage] = [];\n");
      out.write("                addCheck= false;\n");
      out.write("                if(filterObject.package){\n");
      out.write("                    $.each(filterObject.package,function(key1,value1){\n");
      out.write("                        if($(obj).prop('checked')){\n");
      out.write("                        if(value1 == value.id || String(value1).split('/')[0]===String(value.id).split('-')[0] || String(value1).split('-')[0] === String(value.id).split('-')[0]){\n");
      out.write("                                addCheck = true;\n");
      out.write("                                changedPackage.push(value.id);\n");
      out.write("                                avgPackageObj.append('<option value=\"'+value.id+'\" selected=selected>'+value.name+' ['+value.version+']</option>');\n");
      out.write("                            }\n");
      out.write("                        }else if(value1 == value.id){\n");
      out.write("                                addCheck = true;\n");
      out.write("                                changedPackage.push(value.id);\n");
      out.write("                                avgPackageObj.append('<option value=\"'+value.id+'\" selected=selected>'+value.name+' ['+value.version+']</option>');\n");
      out.write("                        }\n");
      out.write("                    });\n");
      out.write("                }\n");
      out.write("                if(!addCheck)\n");
      out.write("                    avgPackageObj.append('<option value=\"'+value.id+'\">'+value.name+' ['+value.version+']</option>')        \n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("       else if(($(obj).prop('checked') && value.status===\"ACTIVE\") || !$(obj).prop('checked'))\n");
      out.write("            packageListDashboard[prevPackage].push({name:value.name,id:value.id});\n");
      out.write("        $(avgPackageObj).find('option').each(function() {\n");
      out.write("            $(this).prevAll('option[value=\"' + this.value + '\"]').remove();\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("    avgPackageObj.attr('widgetId',widgetStateId);\n");
      out.write("    avgPackageObj.chosen();\n");
      out.write("    avgPackageObj.next().css('width',410);\n");
      out.write("    avgPackageObj.next().find('li.search-field input').css('width',250);\n");
      out.write("    avgPackageObj.next().find('li.search-field input').css('height',25);\n");
      out.write("    if(filterObject.package)        \n");
      out.write("        fetchFilterProcessesAVG('',changedPackage,widgetStateId);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function applyAVGFilter(obj){\n");
      out.write("    var widgetStateId = $(obj).attr(\"widgetId\");\n");
      out.write("    var widgetObject = getWidgetObject(widgetStateId);\n");
      out.write("    var filterObject = {};\n");
      out.write("    var modalObj = $(obj).closest('.modal');\n");
      out.write("    var data = {}\n");
      out.write("    var oldObject = JSON.parse( JSON.stringify( widgetObject.filter));\n");
      out.write("\t\tdelete oldObject.chartType;\n");
      out.write("    var checkModalName = true;\n");
      out.write("    var checkProcess = true;\n");
      out.write("\n");
      out.write("\tif($(modalObj).find('.chartName').val()==\"\"){\n");
      out.write("\t\t$(modalObj).find('.error-Msg').removeClass('hide').text($('#widgetChartNameErrorMsg').text());\n");
      out.write("\t\t$(modalObj).find('.chartName').focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\telse if($(modalObj).find('.AVGPackageList').val()==null){\n");
      out.write("\t\t$(modalObj).find('.error-Msg').removeClass('hide').text($('#widgetPackageErrorMsg').text());\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\telse if($(modalObj).find('.AVGProcessesList').val()==null){\n");
      out.write("\t\t$(modalObj).find('.error-Msg').removeClass('hide').text($('#widgetProcessErrorMsg').text());\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("    \n");
      out.write("\tif ($(modalObj).find('.fromDate').val() != undefined && $(modalObj).find('.fromDate').val() != ''){\n");
      out.write("        data.since = $(modalObj).find('.fromDate').val();\n");
      out.write("        filterObject.fromDate = $(modalObj).find('.fromDate').val();\n");
      out.write("    } else \n");
      out.write("        delete data.since;\n");
      out.write("    if ($(modalObj).find('.toDate').val() != undefined  && $(modalObj).find('.toDate').val() != ''){\n");
      out.write("        data.until = $(modalObj).find('.toDate').val();\n");
      out.write("        filterObject.toDate = $(modalObj).find('.toDate').val();\n");
      out.write("    } else \n");
      out.write("        delete data.until;\n");
      out.write("    if ($(modalObj).find('.chartTypes').val() != undefined && $(modalObj).find('.chartTypes').val() != null ){\n");
      out.write("        filterObject.chartType = $(modalObj).find('.chartTypes').val();\n");
      out.write("    }\n");
      out.write("    if ($(modalObj).find('.chartName').val() != undefined && $(modalObj).find('.chartName').val() != null && $.trim($(modalObj).find('.chartName').val()) != ''){\n");
      out.write("            widgetObject.title = $(modalObj).find('.chartName').val();\n");
      out.write("            $('#'+widgetStateId).find('.widget-name').text($(modalObj).find('.chartName').val()); \n");
      out.write("    } else {\n");
      out.write("        checkModalName = false;\n");
      out.write("    }\n");
      out.write("    if ($(modalObj).find('.AVGPackageList').val() != undefined  && $(modalObj).find('.AVGPackageList').val() != ''){\n");
      out.write("        filterObject.package = $(modalObj).find('.AVGPackageList').val();\n");
      out.write("        //data.role = $(modalObj).find('.AVGPackageList').val();\n");
      out.write("        if ($(modalObj).find('.AVGProcessesList').val() != undefined  && $(modalObj).find('.AVGProcessesList').val() != ''){\n");
      out.write("            filterObject.process = $(modalObj).find('.AVGProcessesList').val();\n");
      out.write("            data.process = $(modalObj).find('.AVGProcessesList').val();\n");
      out.write("        } else {\n");
      out.write("            checkProcess = false;\n");
      out.write("            $(modalObj).find('.error-Msg td').text($('#widgetProcessErrorMsg').text());\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    var activeOnly = $(modalObj).find('.AVGActiveProc').prop('checked');\n");
      out.write("    data.activeOnly = activeOnly;\n");
      out.write("    filterObject.activeProcess = activeOnly;\n");
      out.write("    widgetObject.filter = filterObject;\n");
      out.write("    persistWidget(widgetObject);\n");
      out.write("    var newObject = JSON.parse( JSON.stringify( filterObject ) )\n");
      out.write("\tdelete newObject.chartType;\n");
      out.write("\tif (compareObjects(newObject,oldObject)){\n");
      out.write("\t\t$('#avgChartFilter'+widgetStateId).modal('hide');\n");
      out.write("\t\tchangeChartTypeAVG(widgetStateId);\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\tif (checkModalName){\n");
      out.write("\t\t\tif (checkProcess){\n");
      out.write("\t\t\t\t$('#avgChartFilter'+widgetStateId).modal('hide');\n");
      out.write("\t\t\t\tclickRefresh($('#'+widgetStateId).find('.widget-header'),true);\n");
      out.write("\t\t\t\tsendAjaxCall('dashboard/widgets/processAverageCompletionTime', \"POST\", false, true, \"json\", data, avgComErrorCall, function(data1){ \n");
      out.write("\t\t\t\t\tclickRefresh($('#'+widgetStateId).find('.widget-header'),false);\n");
      out.write("\t\t\t\t\tif(responseData.error_message == undefined)\n");
      out.write("\t\t\t\t\t\tpopulateAvgCompTimeData(data1,widgetStateId) ;\n");
      out.write("\t\t\t\t\telse\n");
      out.write("\t\t\t\t\t\tshowErrorNotification(responseData.error_message);\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$(modalObj).find('.error-Msg').removeClass('hide');\n");
      out.write("\t\t\t}\n");
      out.write("\t\t} else{\n");
      out.write("\t\t\t$(modalObj).find('.error-Msg td').text($('#widgetChartNameErrorMsg').text());\n");
      out.write("\t\t\t$(modalObj).find('.error-Msg').removeClass('hide');\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function changeChartTypeAVG(widgetId){\n");
      out.write("\tvar chartRef = FusionCharts(\"AvgCompletionTime\" + widgetId);\n");
      out.write("\trenderChart_AVG(chartRef.getJSONData(),widgetId)\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkFilterAVG(obj){\n");
      out.write("\tvar widgetId = $(obj).closest('.modal').find('.applyButton').attr('widgetId');\n");
      out.write("\tvar widgetObject = getWidgetObject(widgetId);\n");
      out.write("    clickRefresh($('#'+widgetId).find('.widget-header'),false);\n");
      out.write("\tif(widgetObject==undefined || widgetObject.filter.process==undefined)\n");
      out.write("\t\t$(obj).closest('.widget-body').find('.chart').text($('#widgetProcessFilterErrorMsg').text());\n");
      out.write("\tmodalHide($(obj).closest('.modal').attr('id'));\n");
      out.write("}\n");
      out.write("\n");
      out.write("function fetchFilterProcessesAVG(obj,pkgList,widgetId){\n");
      out.write("    var processesInPackege,widgetStateId,avgProcObj;\n");
      out.write("    if ($(obj).length !=0 ){\n");
      out.write("        widgetStateId = $(obj).attr('widgetId');\n");
      out.write("        processesInPackege = $(obj).val();\n");
      out.write("    } else {\n");
      out.write("        widgetStateId = widgetId;\n");
      out.write("        processesInPackege = pkgList;\n");
      out.write("    }\n");
      out.write("    var widgetObject = getWidgetObject(widgetStateId);\n");
      out.write("    var modalObj = $('#avgChartFilter'+widgetStateId);\n");
      out.write("    avgProcObj = $(modalObj).find('.AVGProcessesList');\n");
      out.write("    var prevProcessList = avgProcObj.val();\n");
      out.write("    if($(obj).length == 0){\n");
      out.write("        if (widgetObject && widgetObject.filter){\n");
      out.write("            var filterObject = widgetObject.filter;\n");
      out.write("            if (filterObject.process)\n");
      out.write("                prevProcessList = filterObject.process;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    $(modalObj).find('.error-Msg').addClass('hide');\n");
      out.write("    avgProcObj.removeAttr('style').removeClass('chzn-done');\n");
      out.write("    avgProcObj.next().remove();\n");
      out.write("    avgProcObj.empty();\n");
      out.write("\n");
      out.write("    if(processesInPackege && processesInPackege.length >0){\n");
      out.write("        $.each(processesInPackege,function(key,value){\n");
      out.write("            $.each(packageListDashboard[value],function(key1,value1){\n");
      out.write("                if(prevProcessList && prevProcessList.length >0){\n");
      out.write("                    var checkFlag = false;\n");
      out.write("                    $.each(prevProcessList,function(key2,value2){\n");
      out.write("                        if($(modalObj).find('.AVGActiveProc').prop('checked')){\n");
      out.write("                           if(value2==value1.id || value2.split('}')[1].split('-')[0]===String(value1.id).split('}')[1].split('-')[0]){\n");
      out.write("                                checkFlag=true;\n");
      out.write("                                avgProcObj.append('<option value=\"'+value1.id+'\" selected>'+value1.name+'</option>');\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                        else if(value2==value1.id){\n");
      out.write("                            checkFlag=true;\n");
      out.write("                            avgProcObj.append('<option value=\"'+value1.id+'\" selected>'+value1.name+'</option>');\n");
      out.write("                        }\n");
      out.write("                    });\n");
      out.write("                    if(checkFlag==false)\n");
      out.write("                        avgProcObj.append('<option value=\"'+value1.id+'\">'+value1.name+'</option>');\n");
      out.write("                }\n");
      out.write("                else\n");
      out.write("                    avgProcObj.append('<option value=\"'+value1.id+'\">'+value1.name+'</option>');\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("        $(avgProcObj).find('option').each(function() {\n");
      out.write("            $(this).prevAll('option[value=\"' + this.value + '\"]').remove();\n");
      out.write("        });\n");
      out.write("        avgProcObj.chosen({max_selected_options: 10});\n");
      out.write("\t\tavgProcObj.unbind(\"liszt:maxselected\").bind(\"liszt:maxselected\", function (){\n");
      out.write("\t\t\t$(modalObj).find('.error-Msg').removeClass('hide').text($('#widgetProcessMaxErrorMsg').text());\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t});\n");
      out.write("        avgProcObj.next().css('width',410);\n");
      out.write("        avgProcObj.next().find('li.search-field input').css('width',250).css('height',25);\n");
      out.write("        avgProcObj.closest('tr').removeClass('hide');\n");
      out.write("    } else \n");
      out.write("        avgProcObj.closest('tr').addClass('hide');\n");
      out.write("}\n");
      out.write("\n");
      out.write("function removeErrorMsgAVG(obj){\n");
      out.write("    $(obj).closest('table').find('error-Msg').addClass('hide');\n");
      out.write("}\n");
      out.write("\n");
      out.write("function avgComErrorCall(e){\n");
      out.write("\tif(e.responseText!=null && e.responseText!=undefined)\n");
      out.write("\t\t\tshowInformation(e.responseText);\n");
      out.write("\telse\n");
      out.write("\t\tshowInformation($(\"#widgetAjaxErrorMsg\").text());\n");
      out.write("\treturn false;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/**\n");
      out.write(" * @Function Name : populateAvgCompTimeData\n");
      out.write(" * @Description   : creates a chart data for popluating it in to chart\n");
      out.write(" * @param         : Json object,query fetch / refresh\n");
      out.write(" * @returns       : chartData\n");
      out.write(" * */\n");
      out.write("\n");
      out.write("function populateAvgCompTimeData(data, widgetId) {\n");
      out.write("    var chartData = '{\"chart\":{\"formatnumberscale\": \"0\",\"bgColor\":\"FFFFFF,FFFFFF\",\"showBorder\":\"0\",\"yAxisName\":\"Seconds\", \"useroundedges\": \"1\", \"showalternatevgridcolor\": \"1\",\"canvasbgcolor\":\"#fafbf9\"},'\n");
      out.write("    var dataSet = '\"data\": [';\n");
      out.write("    var count = 0;\n");
      out.write("\tif(!isObjectEmpty(data.average_completion_time))\n");
      out.write("\t{\n");
      out.write("        $.each(data.average_completion_time, function (key, value) {\n");
      out.write("            var seconds = (parseInt(value) / 1000);\n");
      out.write("            key = key.substr(parseInt(key.indexOf(\"}\") + 1), parseInt(key.indexOf(\")\")));\n");
      out.write("            key = key.replace('-', ' - ').replace(')','');\n");
      out.write("            dataSet += '{\"value\" : \"' + parseInt(seconds) + '\"' + \",\" + '\"label\" : \"' + key + '\"},';\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    dataSet = dataSet.substr(0, dataSet.length - 1);\n");
      out.write("    chartData = chartData + \"\" + dataSet + \"]}\";\n");
      out.write("    renderChart_AVG(chartData,widgetId);\n");
      out.write("}\n");
      out.write("\n");
      out.write("/** @Function Name   : renderChart_AVG\n");
      out.write(" *   @Description     : renders the actual chart\n");
      out.write(" *   @param           : chart type,data to render\n");
      out.write(" *   @returns         : chart\n");
      out.write(" * */\n");
      out.write("\n");
      out.write("function renderChart_AVG(data,widgetId){\n");
      out.write("    var widgetObject = getWidgetObject(widgetId);\n");
      out.write("    var filterObject = widgetObject.filter;\n");
      out.write("    var chartType_AVG;\n");
      out.write("    if (filterObject.chartType != undefined && filterObject.chartType != null)\n");
      out.write("        chartType_AVG = filterObject.chartType;\n");
      out.write("    else\n");
      out.write("\t\tchartType_AVG = defaults.swf3;\n");
      out.write("\n");
      out.write("    FusionCharts.setCurrentRenderer('javascript');\n");
      out.write("    if (FusionCharts(\"AvgCompletionTime\" + widgetId) != undefined && FusionCharts(\"AvgCompletionTime\" + widgetId) != null)\n");
      out.write("        FusionCharts(\"AvgCompletionTime\" + widgetId).dispose();\n");
      out.write("    var AvgComplTime = new FusionCharts(\"widgets/swf/\" + chartType_AVG, \"AvgCompletionTime\" + widgetId);\n");
      out.write("    AvgComplTime.setJSONData(data);\n");
      out.write("    data = AvgComplTime.getJSONData();\n");
      out.write("\tif(!isObjectEmpty(data)) \n");
      out.write("\t{\n");
      out.write("    if (chartType_AVG.indexOf(\"Pie\") != -1 || chartType_AVG.indexOf(\"Doughnut\") != -1) {\n");
      out.write("        data.chart.showlabels = 0;\n");
      out.write("        data.chart.showlegend = 1;\n");
      out.write("        data.chart.showvalues = 0;\n");
      out.write("    } else {\n");
      out.write("        data.chart.showlabels = 1;\n");
      out.write("        data.chart.showvalues = 1;\n");
      out.write("        data.chart.showlegend = 0;\n");
      out.write("    }\n");
      out.write("    if (chartType_AVG.indexOf(\"2D\") >= 0) {\n");
      out.write("        if (data.chart.pieradius == null) {\n");
      out.write("            data.chart.pieRadius = 80;\n");
      out.write("        }\n");
      out.write("    } else {\n");
      out.write("        delete data.chart.pieradius;\n");
      out.write("    }\n");
      out.write("\t}\n");
      out.write("    AvgComplTime.setJSONData(data);\n");
      out.write("    AvgComplTime.setTransparent(true);\n");
      out.write("    AvgComplTime.render(defaults.chart1 + widgetId);\n");
      out.write("}\n");
      out.write("\n");
      out.write("$('.chartName').parent().prev().text($('#widgetChartName').text());\n");
      out.write("$('.AVGPackageList').parent().prev().text($('#widgetPackages').text());\n");
      out.write("$('.AVGProcessesList').parent().prev().text($('#widgetProcesses').text());\n");
      out.write("$('.fromDate').closest('td').prev().text($('#widgetFromDate').text());\n");
      out.write("$('.toDate').closest('td').prev().text($('#widgetToDate').text());\n");
      out.write("$('.chartTypes').parent().prev().text($('#widgetChartType').text());\n");
      out.write("$('.groupBy').parent().prev().text($('#widgetFilterGroupBy').text());\n");
      out.write("$('.applyButton').text($('#widgetFilterApply').text());\n");
      out.write("$('.avgLabelActiveProcess').text($(\"#widgetActiveProcess\").text());\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<div id='average_completion_time' class=\"chart\"></div>\n");
      out.write("<div id=\"avgChartFilter\" class=\"modal fade\" tabindex=\"-1\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("                    aria-hidden=\"true\" onclick='javascript:checkFilterAVG(this);'>&times;</button>\n");
      out.write("                <span class=\"modal_heading\">Average Instance Completion Time</span>\n");
      out.write("            </div>\n");
      out.write("             <div class=\"modal-body\">\n");
      out.write("                <table class=\"table noLines chartFilterTable\">\n");
      out.write("                    <tr><td class=\"error-Msg text-danger hide\" colspan=\"2\"></td></tr>\n");
      out.write("                    <tr><td></td><td colspan=\"3\"><input type=\"text\" class=\"chartName\" maxlength=\"50\"></td></tr>\n");
      out.write("                    <tr class='avgActiveProcess'>\n");
      out.write("                        <td class='avgLabelActiveProcess'></td>\n");
      out.write("                        <td colspan=\"3\">\n");
      out.write("                        <label class=\"inline\">\n");
      out.write("                        <input onchange='updateAVGPackages(this)' type=\"checkbox\" class=\"AVGActiveProc ace ace-switch ace-switch-5\">\n");
      out.write("                            <span class=\"lbl\"></span>\n");
      out.write("                        </label>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td></td>\n");
      out.write("                        <td colspan=\"3\"><select multiple class=\"AVGPackageList\" onchange=\"fetchFilterProcessesAVG(this);\" data-placeholder=\"Select Packages\"><option value=\"-1\">Select Package</option></select></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr class=\"hide\">\n");
      out.write("                        <td></td>\n");
      out.write("                        <td colspan=\"3\"><select multiple class=\"AVGProcessesList\" data-placeholder=\"Select Processes\" onchange=\"removeErrorMsgAVG(this);\"><option value=\"-1\">Select Process</option></select></td>\n");
      out.write("                    </tr>\n");
      out.write("                    \n");
      out.write("                    <tr>\n");
      out.write("                        <td></td>\n");
      out.write("                        <td>\n");
      out.write("                           <div class=\"input-group pull-left\">\n");
      out.write("                              <input type=\"text\" class=\"chartFilterDates fromDate pull-left\" data-date-format=\"yyyy-mm-dd\">\n");
      out.write("                              <span class=\"input-group-addon\">\n");
      out.write("                                 <i class=\"fa fa-calendar bigger-110\"></i>\n");
      out.write("                              </span>\n");
      out.write("                           </div>\n");
      out.write("                        </td>\n");
      out.write("                        <td></td>\n");
      out.write("                        <td>\n");
      out.write("                           <div class=\"input-group pull-left\">\n");
      out.write("                              <input type=\"text\" class=\"chartFilterDates toDate pull-left\" data-date-format=\"yyyy-mm-dd\">\n");
      out.write("                              <span class=\"input-group-addon\">\n");
      out.write("                                 <i class=\"fa fa-calendar bigger-110\"></i>\n");
      out.write("                              </span>\n");
      out.write("                           </div>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td></td>\n");
      out.write("                        <td><select class=\"chartTypes\"></select></td>\n");
      out.write("                    </tr>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button class=\"btn btn-primary btn-sm applyButton\" type=\"button\" aria-hidden=\"true\" onclick=\"applyAVGFilter(this);return false;\"></button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
