version: '2'
services:
  florida_blue_pg:
    # build: ./pg
    image: estebanf/florida_blue_pg
    ports: 
      - "5432:5432"
    container_name: florida_blue_pg
  florida_blue_bpms:
    image: estebanf/intalio_dev:875
    ports: 
      - "8080:8080"
      - "9092:9092"
    container_name: florida_blue_bpms
    links: 
      - florida_blue_pg
    depends_on: 
      - florida_blue_pg
    extra_hosts: 
      - "bpms.local:127.0.0.1"
