version: '2'
services:
  ibpms_files:
    image: estebanf/ibpms_ha_files
    container_name: ibpms_files
  ibpms_mysql:
    image: estebanf/ibpms_ha_mysql
    ports:
      - "3306:3306"
    container_name: ibpms_mysql
  ibpms_server1:
    image: estebanf/ibpms_ha_server
    container_name: ibpms_server1
    environment:
      NODE: 01
    volumes_from:
      - ibpms_files
    links:
      - ibpms_mysql
    depends_on:
      - ibpms_mysql
    extra_hosts: 
      - "bpms.local:127.0.0.1"      
  ibpms_server2:
    image: estebanf/ibpms_ha_server
    container_name: ibpms_server2
    environment:
      NODE: 02
    volumes_from:
      - ibpms_files
    links:
      - ibpms_mysql
    depends_on:
      - ibpms_mysql
    extra_hosts: 
      - "bpms.local:127.0.0.1"      
  ibpms_server3:
    image: estebanf/ibpms_ha_server
    container_name: ibpms_server3
    environment:
      NODE: 03
    volumes_from:
      - ibpms_files
    links:
      - ibpms_mysql
    depends_on:
      - ibpms_mysql
    extra_hosts:
      - "bpms.local:127.0.0.1"
  ibpms_balancer:
    image: estebanf/ibpms_ha_balancer
    container_name: ibpms_balancer
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - ibpms_server1
      - ibpms_server2
      - ibpms_server3
