<wsdl:definitions targetNamespace="urn:intalio.com:connectors:database:budgeting:insert_attachmentservice" xmlns:tns="urn:intalio.com:connectors:database:budgeting:insert_attachmentservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:intalio.com:connectors:database:budgeting:insert_attachmentservice">
    <wsdl:types>
        <xsd:schema>
            <xsd:import schemaLocation="insert_attachment.xsd" namespace="urn:intalio.com:connectors:database:budgeting:insert_attachmentservice"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="insert_attachmentInput">
        <wsdl:part name="parameters" element="ns:insert_attachmentParameterSet"/>
    </wsdl:message>
    <wsdl:message name="insert_attachmentOutput">
        <wsdl:part name="parameters" element="ns:insert_attachmentResultSet"/>
    </wsdl:message>
    <wsdl:message name="insert_attachmentFault">
        <wsdl:part name="fault" element="ns:insert_attachmentFault"/>
    </wsdl:message>
    <wsdl:portType name="insert_attachmentPort">
        <wsdl:operation name="insert_attachment">
            <wsdl:input message="tns:insert_attachmentInput"/>
            <wsdl:output message="tns:insert_attachmentOutput"/>
            <wsdl:fault message="tns:insert_attachmentFault" name="nsinsert_attachmentFault"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="insert_attachmentPortSoapBinding" type="tns:insert_attachmentPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="insert_attachment">
            <soap:operation style="document" soapAction="urn:intalio:connector:jdbc:query:insert_attachment"/>
            <wsdl:input>
                <soap:body namespace="urn:intalio.com:connectors:database:budgeting:insert_attachmentservice" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="urn:intalio.com:connectors:database:budgeting:insert_attachmentservice" use="literal"/>
            </wsdl:output>
            <wsdl:fault name="nsinsert_attachmentFault">
                <soap:body namespace="urn:intalio.com:connectors:database:budgeting:insert_attachmentservice" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="insert_attachmentService">
        <wsdl:port binding="tns:insert_attachmentPortSoapBinding" name="insert_attachmentPort">
            <soap:address location="http://bpms.local:8080/everteam/ode/processes/Budgeting/Connectors/Database/insert_attachment"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>